### ISSUE TITLE
Throw exception on converting repeating decimal to wei

### ISSUE THREAD

**Issue by roypun** [Nethereum/Nethereum#100]
I was trying to convert a decimal number to wei:
<pre>
var ether = (decimal)1 / 3;
var wei = UnitConversion.Convert.ToWei(ether, UnitConversion.EthUnit.Ether);
</pre>
I got the same result  on both 1.0.2 and 1.0.6:
<pre>
System.OverflowException: Arithmetic operation resulted in an overflow.
at System.Convert.ToInt64(Double value)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.CalculateNumberOfDecimalPlaces(Decimal value, Int32 currentNumberOfDecimals)
at Nethereum.Web3.UnitConversion.ToWei(Decimal amount, BigInteger fromUnit)
at Nethereum.Web3.UnitConversion.ToWei(Decimal amount, EthUnit fromUnit)
</pre>

**Comment by juanfranblanco** [comment]
Many thanks,

Please check the latest fix https://github.com/Nethereum/Nethereum/blob/4678ad71216072a7613f85d53e846c7f4b280309/src/Nethereum.Util/UnitConversion.cs
