### ISSUE TITLE
GetSubscriptionDataResponsesAsObservable Won't stream data after a while 

### ISSUE THREAD

**Issue by Neo-vortex** [Nethereum/Nethereum#1039]
I am using this simplified code to listen to new block events :

```csharp
 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {

        await Task.Run(async () =>
        {
            while (true)
            {
                logger.LogInformation("starting new block subscription listener");
                try
                {
                    var client= new StreamingWebSocketClient(configuration.GetSection("RpcUrlWebsocket").Value, log: logger);
                    var subscription = new EthNewBlockHeadersObservableSubscription(client);
                    var subscriptionIdObservable = subscription.GetSubscribeResponseAsObservable();
                    var newBlockObservable = subscription.GetSubscriptionDataResponsesAsObservable();

                    // Subscribe to the subscription response to log the subscription ID
                    subscriptionIdObservable.Subscribe(subscriptionId =>
                    {
                        logger.LogInformation("Subscribed to new blocks with ID: {SubscriptionId}", subscriptionId);
                    });

                    // Subscribe to new block notifications and handle errors
                    newBlockObservable.Subscribe(
                        block => { _ = PublishNewBlock(block); },
                        ex =>
                        {
                            logger.LogWarning("Error in new block subscription: {ErrorMessage}", ex.Message);
                            subscription.UnsubscribeAsync();
                            _ = ExecuteAsync(CancellationToken.None);
                        }, () =>
                        {
                            logger.LogWarning("New block subscription stoped gracefully and unintended");
                            subscription.UnsubscribeAsync();
                            _ = ExecuteAsync(CancellationToken.None);
                        });


                    await client.StartAsync();
                    await subscription.SubscribeAsync();

                    // Wait for the stopping token to be cancelled
                    await Task.Delay(Timeout.Infinite, stoppingToken);

                    await subscription.UnsubscribeAsync();
                }
                catch (Exception ex)
                {
                    logger.LogError("Exception in subscription process: {ExceptionMessage}", ex.Message);
                }

                // Wait a bit before retrying to avoid a tight loop in case of persistent errors
                await Task.Delay(TimeSpan.FromSeconds(5), stoppingToken);
            }
        }, stoppingToken);
    }

```

According to [this](https://docs.nethereum.com/en/latest/nethereum-subscriptions-streaming/#subscription-considerations), i know that if websocket fails I will have to resubscribe which I think I am doing in this line : 
```csharp
  ex =>
                        {
                            logger.LogWarning("Error in new block subscription: {ErrorMessage}", ex.Message);
                            subscription.UnsubscribeAsync();
                            _ = ExecuteAsync(CancellationToken.None);
                        }
```
I can also confirm this mechanism works in case of a network failure:

```bash
warn: ChainTide.Services.NewBlockNotification[0]
      Error in new block subscription: Client connection error
fail: ChainTide.Services.NewBlockNotification[0]
      RPC Exception, RPC Request: {"id":"b390535b-2193-46c6-8b1a-ddb24af8f1a6","jsonrpc":"2.0","method":"eth_unsubscribe","params":["0x3d95198a5ee1979cbd7f584f113eb7c3"]}
      System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
         at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
         at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequestMessage request, IRpcStreamingResponseHandler requestResponseHandler, String route)
info: ChainTide.Services.NewBlockNotification[0]
      starting new block subscription listener
info: ChainTide.Services.NewBlockNotification[0]
      Subscribed to new blocks with ID: 0xf1f8edf9edd6b38936e3fca16ac9caa1
info: ChainTide.Services.NewBlockNotification[0]
      New block: 20389002
info: ChainTide.Application.Commands.Handlers.EthereumValueTraceCommandHandler[0]
      EthereumValueTraceCommandHandler starte
``` 
It continues to work as expected.
But after a while no new data will come and no exception will be thrown, also I will hit 100% CPU usage on a single core.
No Exception, nothing.
 
## Expected Behavior
stream continues to feed data or an exception is thrown

## Current Behavior
data streaming stops without Exception

ENV:
```
dotnet 8
netherume 4.21.2
ubuntu 24
```
P.S
maybe also partially related https://github.com/Nethereum/Nethereum/issues/998

**Comment by juanfranblanco** [comment]
Hi @Neo-vortex this is known behaviour of clients, that need to be pinged to continue working.. https://github.com/Nethereum/Nethereum.Templates.WebSocketStreaming/blob/master/ExampleLogsUniswapSyncSubscription.cs#L70-L76
