### ISSUE TITLE
Error to deserialize eth_blockNumber response

### ISSUE THREAD

**Issue by brunocasarotti** [Nethereum/Nethereum#1047]
Trying out OpenCampus network and I am facing some issues to get latest block number. It works fine in Postman but fails to deserialize when using Nethereum. RPC: https://opencampus-codex.blockscout.com/api/eth-rpc

It fails when executing this code:
```
var lastBlockInBlockchain =
            await web3.Eth.Blocks.GetBlockNumber.SendRequestAsync(BlockParameter.CreateLatest());
```

Error:

```
2024-09-12T21:56:51 [21:56:51.543  DBG] [Microsoft.Extensions.Hosting.Internal.Host] Hosting starting
2024-09-12T21:56:59 Unhandled exception. Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_blockNumber
2024-09-12T21:56:59  ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: l. Path 'id', line 1, position 40.
2024-09-12T21:56:59    at Newtonsoft.Json.JsonTextReader.ParseValue()
2024-09-12T21:56:59    at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
2024-09-12T21:56:59    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
2024-09-12T21:56:59    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2024-09-12T21:56:59    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-12T21:56:59    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2024-09-12T21:56:59    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2024-09-12T21:56:59    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2024-09-12T21:56:59    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
2024-09-12T21:56:59    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
2024-09-12T21:56:59    at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
2024-09-12T21:56:59    --- End of inner exception stack trace ---
2024-09-12T21:56:59    at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
2024-09-12T21:56:59    at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
2024-09-12T21:56:59    at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
```

Nethereum.Web3 version 4.21.4 also on 4.14.0

**Comment by juanfranblanco** [comment]
@brunocasarotti you are passing the wrong parameter

check this example, you can run it in the playground https://playground.nethereum.com/csharp/id/1002

using System;
using System.Text;
using Nethereum.Hex.HexConvertors.Extensions;
using System.Threading.Tasks;
using Nethereum.Web3;
using Nethereum.RPC.Eth.Blocks;
using Nethereum.Hex.HexTypes;

public class EthRpcCalls_BlockNumber_Block_Transaction_Receipt
{
    private static async Task Main(string[] args)
    {
        //Connecting to Ethereum mainnet using Infura
        var web3 = new Web3(" https://opencampus-codex.blockscout.com/api/eth-rpc");

        //Getting current block number  
        var blockNumber = await web3.Eth.Blocks.GetBlockNumber.SendRequestAsync();
        Console.WriteLine("Current BlockNumber is: " + blockNumber.Value);

        //Getting current block with transactions 
        var block = await web3.Eth.Blocks.GetBlockWithTransactionsByNumber.SendRequestAsync(new HexBigInteger(100));
        Console.WriteLine("Block number: " + block.Number.Value);
        Console.WriteLine("Block hash: " + block.BlockHash);
        Console.WriteLine("Block no of transactions:" + block.Transactions.Length);
        Console.WriteLine("Block transaction 0 From:" + block.Transactions[0].From);
        Console.WriteLine("Block transaction 0 To:" + block.Transactions[0].To);
        Console.WriteLine("Block transaction 0 Amount:" + block.Transactions[0].Value);
        Console.WriteLine("Block transaction 0 Hash:" + block.Transactions[0].TransactionHash);

        var transaction =
            await web3.Eth.Transactions.GetTransactionByHash.SendRequestAsync(
                block.Transactions[0].TransactionHash);
        Console.WriteLine("Transaction From:" + transaction.From);
        Console.WriteLine("Transaction To:" + transaction.To);
        Console.WriteLine("Transaction Amount:" + transaction.Value);
        Console.WriteLine("Transaction Hash:" + transaction.TransactionHash);

        var transactionReceipt =
            await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(
                block.Transactions[0].TransactionHash);
        Console.WriteLine("Transaction Hash:" + transactionReceipt.TransactionHash);
        Console.WriteLine("TransactionReceipt Logs:" + transactionReceipt.Logs.Count);
    }
}
