### ISSUE TITLE
"The method personal_unlockAccount does not exist/is not available"

### ISSUE THREAD

**Issue by heyalistair** [Nethereum/Nethereum#105]
I can't seem to unlock an account without getting an RpcResponseException error. I have just downloaded nethereum and gone through the tutorial video for macOS in the README.md by @juanfranblanco 

Here are the steps that I have taken.

1) Start a dev chain
`➜  geth --dev --rpc`

2) Created an account
```
➜  devchain geth attach ipc:///var/folders/_4/m3s1z7kn4_g5ytf_ysty6txm0000gn/T/ethereum_dev_mode/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.5.9-stable-a07539fb/darwin/go1.8
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 shh:1.0 txpool:1.0 web3:1.0

> personal.newAccount('password')
"0xe48b4653172a0316be374909ab0bc814fb59cb0c"
```

3) Unlock account
```
using System.Threading.Tasks;
using Nethereum.Hex.HexTypes;

namespace Nethereum.Tutorials
{
    public class Deployment
    {
        public async Task ShouldBeAbleToDeployContract()
        {
            var senderAddress = "0xe48b4653172a0316be374909ab0bc814fb59cb0c";
            var password = "password";

            var web3 = new Web3.Web3();

            // open account
            bool unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(60));
         }
    }
}
``` 

And then here is the stack trace:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (The method personal_unlockAccount does not exist/is not available) ---> Nether
eum.JsonRpc.Client.RpcResponseException: The method personal_unlockAccount does not exist/is not available
   at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.<SendRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.RPC.Personal.PersonalUnlockAccount.<SendRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nethereum.Tutorials.Deployment.<ShouldBeAbleToDeployContract>d__0.MoveNext() in /Users/alistair/code/nethereum/Deployment/Deployment.cs:line 21
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApplication.Program.Run() in /Users/alistair/code/nethereum/Program.cs:line 17
   at ConsoleApplication.Program.Main(String[] args) in /Users/alistair/code/nethereum/Program.cs:line 11
```

Any thoughts?

**Comment by juanfranblanco** [comment]
Have you enable "personal" on the RPC api settings when launching geth?
--rpcapi "eth,web3,personal,net,miner,admin,debug"

**Comment by heyalistair** [comment]
Ah yes, thank you very much, I did indeed miss that and I have now enabled it. I am new to `geth`...

It still doesn't completely fix my problem though... Now I have another error with the unlock account. Any suggestions?

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (invalid argument 2: json: cannot
 unmarshal string into Go value of type uint64) ---> Nethereum.JsonRpc.Client.RpcResponseException: invalid ar
gument 2: json: cannot unmarshal string into Go value of type uint64
   at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.<SendRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.RPC.Personal.PersonalUnlockAccount.<SendRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nethereum.Tutorials.Deployment.<ShouldBeAbleToDeployContract>d__0.MoveNext() in /Users/alistair/code/net
hereum/Deployment/Deployment.cs:line 26
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApplication.Program.Run() in /Users/alistair/code/nethereum/Program.cs:line 17
   at ConsoleApplication.Program.Main(String[] args) in /Users/alistair/code/nethereum/Program.cs:line 11
```

**Comment by juanfranblanco** [comment]
The new version of Geth it only accepts Integers instead of Hex. So just pass 
            bool unlockResult = await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 60);

**Comment by heyalistair** [comment]
Yep, that's the ticket. Works great now. Thanks for your help!

**Comment by haimHadad** [comment]
What am I suppose to do with this line: --rpcapi "eth,web3,personal,net,miner,admin,debug"?
I`m trying to do the same thing as @ heyalistair  but with infura.
