### ISSUE TITLE
Function CallAsync: No parameterless constructor defined for this object.

### ISSUE THREAD

**Issue by Baaleos** [Nethereum/Nethereum#176]
Using Contract code:

```
	function getName() constant returns (byte[100] name){
	    return areaName;
	}
```

Which appears in my abi as:

> {
> 	"constant": true,
> 	"inputs": [],
> 	"name": "getName",
> 	"outputs": [{
> 		"name": "name",
> 		"type": "bytes1[100]"
> 	}],
> 	"payable": false,
> 	"stateMutability": "view",
> 	"type": "function"
> }

And then called via:

```
public string GetName()
        {
            var getString = _theContract.GetFunction("getName");
            var totalGas = getString.EstimateGasAsync().Result;
            var callResult = getString.CallAsync<byte[]>().Result;
            return Encoding.UTF8.GetString(callResult);
        }
```

Produces a 'No parameterless constructor defined for this object'

  

>  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at ConsoleApplication1.Classes.Area.GetName() in d:\Ether\ConsoleApplication1\ConsoleApplication1\Classes\Area.cs:line 28
>    at ConsoleApplication1.Program.DoWork() in d:\Ether\ConsoleApplication1\ConsoleApplication1\Program.cs:line 127
>    at ConsoleApplication1.Program.Main(String[] args) in d:\Ether\ConsoleApplication1\ConsoleApplication1\Program.cs:line 22
>    at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>    at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

Am I missing something?
The function doesn't require any arguments.

If I attempt to do the following:

`var callResult2 = getString.CallAsync<byte[]>(new object[] { "" }).Result;`

I then get 
{"Too many arguments: 1 > 0"}  coming from the Nethereum code.

Is there something wrong with the Parameterless CallAsync method around how it constructs the Task object?
I think it was working for me back in 1.0.6 of Nethereum.Portable.

**Comment by juanfranblanco** [comment]
Have you tried to use a List<byte>() ? instead of a byte[]?

**Comment by Baaleos** [comment]
As in List<byte>()?

Returns: System.Byte is not supported

When I do:
`var callResult = getString.CallAsync<List<byte>>().Result;`

 ```
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConsoleApplication1.Classes.Area.GetName() in d:\Ether\ConsoleApplication1\ConsoleApplication1\Classes\Area.cs:line 29
   at ConsoleApplication1.Program.DoWork() in d:\Ether\ConsoleApplication1\ConsoleApplication1\Program.cs:line 127
   at ConsoleApplication1.Program.Main(String[] args) in d:\Ether\ConsoleApplication1\ConsoleApplication1\Program.cs:line 22
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
```

If I do List<object> - it gets a little further.
It seems to be coming back with a 

List of 100 byte[32]

Eg: 100 instances of a byte[32]
Furthermore - they area all blank.
Eg: Each of the byte[32]'s have all their values set to 0;

Am I missing something - shouldnt I be able to retrieve a byte[100] from the smart contract?
The reason for me using byte[100] is because solidity does not currently support passing dynamic sized types between contracts - so I am specifying an array of 100 etc to facilitate passing the data between contracts.

**Comment by juanfranblanco** [comment]
Have you got an example of the areaName output so I can reproduce it?

**Comment by Baaleos** [comment]
My main code looks like this:

```
            string worldAddress = WorldAdmin.CreateWorld("World"+DateTime.Now.Ticks);
            World w = new World(worldAddress);
            Area a = w.CreateArea();
            a.SetName("Kitchen");
            var name = a.GetName();
```

It looks like something funky might be happening when the SetName function is called - when I do
debug.traceTransaction  it ends up doing over 2000 structLogs - in some cases crashing geth when I try to debug the transaction.

I've changed my setName function to have a debug event present:
```
event SetName(uint status);
	function setName(bytes1[100] name){
	    SetName(0x0);
	    //if(tx.origin != owner){ return;}
	    areaName = name;
	    SetName(0x1);
	}
```

I can see the SetName 0 and 1 both being fired - suggesting that the method finishes.

My SetName function is called via:
```
public void SetName(string description)
        {
            byte[] data = Encoding.UTF8.GetBytes(description);
            byte[] b = new byte[100];
            Array.Copy(data, b, data.Length);
            var web3 = new Web3(Resources.Server);
            var setDesc = _theContract.GetFunction("setName");
            var totalGas = GenericUtil.GetGasPrice(setDesc, b);
            WorldAdmin.UnlockAccountForTransaction();
            var callResult = setDesc.SendTransactionAsync("0x13111c7C98dFb371A4dd6cD1B1D9E6285bE68d2e", totalGas, new HexBigInteger(0), b);
            var theResult = GenericUtil.GetReceiptAsync(callResult.Result);
        }
```

Note - I am copying the content of the string data into a byte[100] to ensure that it meets the contracts requirement.

**Comment by Baaleos** [comment]
Note : my Area contract looks like this presently:

```
contract mortalArea {
			/* Define variable owner of the type address */
	address owner;
	
	address[] objectsInArea;
	mapping (address => uint) ObjectToIndex;
	
	/* This function is executed at initialization and sets the owner of the contract */
	function mortalArea() { owner = tx.origin; }

	/* Function to recover the funds on the contract */
	function kill() returns (bool b) {
		if(tx.origin != owner){ return false;}
	    	selfdestruct(owner);
			return true;
	}
	
	function createObject(bytes objName, bool hasInventory, bool isLocked, address key, Area theArea) returns (AreaObject a){
		if(tx.origin != owner){ return AreaObject(0x0);}
	    	AreaObject newAreaobj = new AreaObject(theArea);
	    	newAreaobj.setInfo(objName, hasInventory, isLocked, key);
	   		objectsInArea.push(newAreaobj);
			return newAreaobj;
		}
	
	function getObjectByIndex(uint i) returns (address a) {
		return objectsInArea[i];
	}
	
	
	function getNumberObjectsInArea() returns (uint a) {
		return objectsInArea.length;
	}
	
	function updateObjectMap(AreaObject obj){
		//Get the object
	            
		if(obj.getOwningArea() != this){
			objectsInArea[ObjectToIndex[obj]] = AreaObject(0x0);
		} 
	}
}

 
contract Area is mortalArea {
	bytes1[100] areaName;
	bytes1[512] areaDesc;
	 
	address owningWorld;
	
	
	function destroy() returns (bool b){
		return mortalArea.kill();
	}
	
	function Area () {
		
	}
	
	function setOwningWorld(World w){
	    owningWorld = w;
	}
	function getOwningWorld() returns (address w){
	    return owningWorld;
	}
	 
	function getName() constant returns (bytes1[100] name){
	    return areaName;
	}
	event SetName(uint status);
	function setName(bytes1[100] name){
	    SetName(0x0);
	    //if(tx.origin != owner){ return;}
	    areaName = name;
	    SetName(0x1);
	}
	 
	
	
	function getObjectsVisibleBy(Player p) returns (uint[100] obs){
	    uint[100] memory objs;
	    if(Area(p.getCurrentArea()) != this){
	        return objs;
	    }
	    uint count = 0x0;
	    uint max = mortalArea.getNumberObjectsInArea();
	    for(uint i=0;i<max;i++){
	        address o = mortalArea.getObjectByIndex(i);
	        if(o != address(0x0) && AreaObject(o).getOwningArea() == this){
	            objs[count] = i;
	            count++;
	        }
	         
	    }
	    return objs;
	}
	 
	
	function setDescription(byte[512] s){
		if(tx.origin != owner){ return;}
		areaDesc = s;
	}
	function getDescription() constant returns (byte[512] s){
		return areaDesc;
	}
	function createObject(bytes objName, bool hasInventory, bool isLocked, address key) returns (AreaObject a){
		var obj = mortalArea.createObject(objName, hasInventory,  isLocked,  key, this);
		obj.setOwningArea(this);
		return obj;
	}
}
```

**Comment by Baaleos** [comment]
debug.traceTransaction("0x19cbe69603e5af0cbd0427d4e47f7d2d8e591e488af934cc3c90b171b3e5db6e").structLogs.length;

Returns over 6000 operations.
This seems rather high for a simple 
`areaName = name;`

In any case- 
It looks like that behavior might not be nethereum and more solidity or something to do with the types I am using.

Although I am still not sure why I am unable to CallAsync with byte[100] as the return type.
It only lets me perform a CallAsync with : 
var callResult2 = getString.CallAsync<List<byte[]>>().Result;

Which is going to be a pain to return fixed length strings of 100 bytes lenth.



On examining the setName transaction:
Disregarding the fact that it had over 6000 structLogs.
The last entry looked like this:

 ```
debug.traceTransaction("0x19cbe69603e5af0cbd0427d4e47f7d2d8e591e488af934cc3c90b171b3e5db6e").structLogs[6365]
{
  depth: 1,
  error: null,
  gas: 10010,
  gasCost: 2,
  memory: ["0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000ce0", "000000000000000000000000000000000000000000000000000000000000004b", "0000000000000000000000000000000000000000000000000000000000000069", "0000000000000000000000000000000000000000000000000000000000000074", "0000000000000000000000000000000000000000000000000000000000000063", "0000000000000000000000000000000000000000000000000000000000000068", "0000000000000000000000000000000000000000000000000000000000000065", "000000000000000000000000000000000000000000000000000000000000006e", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000001"],
  op: "POP",
  pc: 2399,
  stack: ["00000000000000000000000000000000000000000000000000000000e540bf8f", "00000000000000000000000000000000000000000000000000000000000000f6", "0000000000000000000000000000000000000000000000000000000000000060"],
  storage: {
    0000000000000000000000000000000000000000000000000000000000000003: "0000000000000000000000000000000000000000000000000000000000000000",
    0000000000000000000000000000000000000000000000000000000000000004: "0000000000000000000000000000000000000000000000000000000000000000",
    0000000000000000000000000000000000000000000000000000000000000005: "0000000000000000000000000000000000000000000000000000000000000000",
    0000000000000000000000000000000000000000000000000000000000000006: "0000000000000000000000000000000000000000000000000000000000000000"
  }
}

```

**Comment by juanfranblanco** [comment]
I am looking into it as bytes1 should support the output of a single byte, not just an array, but looking at your use case why don't you use a string?

**Comment by Baaleos** [comment]
The reason I could not use string as the storage type in solidity was because solidity does not support passing of string or bytes types between contracts. (dynamic sized types)
Eg: My Area contract would not be able to return its 'getDescription' output to a Player contract who happened to be trying to 'examine' the area that they are in. 
Granted - in my case- it would work for the C# managed code - but it would not work for cross contract interactions within the solidity language. 

I can adapt my use-case in the mean time to work with the string approach.
If the bytes1 issue can be resolved though, I could work around this issue by using fixed sized byte arrays - to have more of the logic inside the EVM.

**Comment by juanfranblanco** [comment]
I have just pushed decoding capability for bytes1 into a single byte array. But for the time being you just need the first byte of the array of each element (if that helps).

**Comment by juanfranblanco** [comment]
Ok, encoding / decoding added.

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/blob/2632b77c44d5a41f108be9f4d27915403442326c/src/Nethereum.Web3.Tests/Issues/Bytes1FixedArraySupport.cs

**Comment by Baaleos** [comment]
Cool - thanks

**Comment by juanfranblanco** [comment]
Regardless of this, check your storage in the EVM. It might be costly and you might get away with some string to byte[] conversion.

**Comment by juanfranblanco** [comment]
https://github.com/Arachnid/solidity-stringutils/blob/master/strings.sol This might help
