### ISSUE TITLE
System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).

### ISSUE THREAD

**Issue by lugrugzo** [Nethereum/Nethereum#184]
When I try to generate a new address through RPC, I get an error.

Method:

``` cs
public override async Task<string> GetNewAddress(string userId)
{
     try
     {
          return await _web3.Personal.NewAccount.SendRequestAsync("yoyo");
     }
     catch (Exception e)
     {
         Console.WriteLine(e);
         throw;
      }
}
```

Error:

``` cs
EdjCase.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__26`2.MoveNext()
   --- End of inner exception stack trace ---
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__26`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Exchange_Server.Payment.Processor.EthereumPaymentProcessor.<GetNewAddress>d__3.MoveNext() in Project/Payment/Processor/EthereumPaymentProcessor.cs:line 97
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__26`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EdjCase.JsonRpc.Client.RpcClient.<SendRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Exchange_Server.Payment.Processor.EthereumPaymentProcessor.<GetNewAddress>d__3.MoveNext() in Project/Payment/Processor/EthereumPaymentProcessor.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Exchange_Server.Payment.Processor.PaymentProcessors.<GetNewAddress>d__7.MoveNext() in Project/Payment/Processor/PaymentProcessors.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Exchange_Server.Services.WalletService.<GenerateNewAddress>d__8.MoveNext() in Project/Services/WalletService.cs:line 103
```

However, there is no error when using web3.js in node.js:

``` js
var Web3 = require('web3')
var web3 = new Web3()

web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545"))

if(!web3.isConnected())
    console.log("not connected");
else
    console.log("connected")

console.log("syncing", web3.eth.syncing)
console.log("block", web3.eth.blockNumber)

var newAccount = web3.personal.newAccount("yoyo");
console.log(newAccount)
```

I'm using `geth` as ethereum client with following arguments:

```geth --light --rpc --rpcapi "personal,eth,web3"```

What can be the problem?

**Comment by juanfranblanco** [comment]
Ill have a look, you have done the first test which is having "personal".

**Comment by juanfranblanco** [comment]
I assumed you are sorted, but I have created a workbook, in case it helps you. https://github.com/Nethereum/Nethereum.Workbooks/blob/master/nethereum-creating-a-new-account-using-geth.workbook.
