### ISSUE TITLE
Unable to find smart contract or byte code for the shared web sample to deploy in block chain and play

### ISSUE THREAD

**Issue by srinivasvinnakota** [Nethereum/Nethereum#229]
Hi,

I tried to download the source code. I have setup Ethereum block chain in Azure and i wanted to deploy smart contracts for the shared web sample (https://github.com/Nethereum/Nethereum/tree/master/src/Nethereum.Web.Sample), I coudnt find the contract, please help me and unblock to help me play & learn

**Comment by nixman2** [comment]
Was trying to run the web sample as well, and it looks like it can't find the contract like @srinivasvinnakota mentioned here. The exception I got was a 502 bad gateway.

`System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at Nethereum.Web.Sample.Controllers.HomeController.Sync[T](Task`1 call) in D:\temp\Nethereum\src\Nethereum.Web.Sample\Controllers\HomeController.cs:line 29
       at Nethereum.Web.Sample.Controllers.HomeController.DaoProposals() in D:\temp\Nethereum\src\Nethereum.Web.Sample\Controllers\HomeController.cs:line 34
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException: 
       HResult=-2146233088
       Message=Error occurred when trying to send rpc requests(s)
       Source=Nethereum.Portable
       StackTrace:
            at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__16.MoveNext() in D:\temp\Nethereum\src\Nethereum.JsonRpc.RpcClient\RpcClient.cs:line 108
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__11`1.MoveNext() in D:\temp\Nethereum\src\Nethereum.JsonRpc.RpcClient\RpcClient.cs:line 47
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext() in D:\temp\Nethereum\src\Nethereum.JsonRpc.Client\ClientBase.cs:line 17
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.Contracts.FunctionBase.<CallAsync>d__17`1.MoveNext() in D:\temp\Nethereum\src\Nethereum.Contracts\FunctionBase.cs:line 51
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.Web.Sample.Services.DaoService.<GetLatestProposals>d__6.MoveNext() in D:\temp\Nethereum\src\Nethereum.Web.Sample\Services\DaoService.cs:line 44
       InnerException: 
            HResult=-2146233088
            Message=Response status code does not indicate success: 502 (Bad Gateway).
            Source=System.Net.Http
            StackTrace:
                 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                 at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__16.MoveNext() in D:\temp\Nethereum\src\Nethereum.JsonRpc.RpcClient\RpcClient.cs:line 95
            InnerException: 
`

**Comment by juanfranblanco** [comment]
Hi,

The web sample uses the old DAO smart contract, pointing to mainnet, this needs to be changed to a simpler smart contract. 

If you want a quick sample to get started check out this: 

http://nethereum.readthedocs.io/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstard-smartcontrats/

**Comment by srinivasvinnakota** [comment]
Thanks Juan,

Currently, i am trying by posting a raw transaction using C# netherum packages. I have set up, ethereum private consortium block chain in Azure.
However, when i am trying to post transaction, seeing error - **"insufficient funds for gas * price + value"** 
I took keystore files from transaction node and took private key (ciphertext) from the key store file specific to the defaul account which i am using to transact.

But when i checked geneis block, ssh to transaction node, noticed there is gas set as default. How should i topup gas in my default account. currently, i am not able to submit any transaction or deploy any contract. Please help.

Geneis Block : 
{
  "alloc": {
    "**e7fba035693df8080f0fa30d91862ec3a9046c75**": {
      "balance": "**1000000000000000000000000000000**"
    }
  },
  "config": {
    "homesteadBlock": 0,
    "chainID": 72,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "nonce": "0x0000000000000042",
  "difficulty": "0x6666",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x4c4b40"
}

**Comment by juanfranblanco** [comment]
What I normally do (we are creating some instructions / docs for this) is to use the faucet to fund a newly created account:
https://github.com/Nethereum/Nethereum/issues/206#issuecomment-349248050.

You should have enough balance for that genesis account nevertheless, if you have the keystore file, you should be able to retrieve the private key using the Nethereum KeyStoreService. Sample here:
https://github.com/Nethereum/Nethereum.Workbooks/blob/master/docs/nethereum-infura-transfer.workbook

**Comment by srinivasvinnakota** [comment]
It worked!!!
Thanks a lot Juan. I am able to submit a signed transaction, after using the private key from above mentioned snippet.

But when trying to deploy a contract, noticing error "**intrinsic gas too low**"

Below is the code. Private key is associated to the same account that is same as sender address i am referring in below code. I am not sure, if this is correct. Can you please help me here.

 var privateKey = "[**Private Key associated to address 0xE7Fba035693dF8080f0FA30d91862EC3A9046c75]**";
            var uri = new Uri("http://[blockchain].westus2.cloudapp.azure.com:8545/");
            var abi = @"[{""constant"":false,""inputs"":[{""name"":""val"",""type"":""int256""}],""name"":""multiply"",""outputs"":[{""name"":""d"",""type"":""int256""}],""type"":""function""},{""inputs"":[{""name"":""multiplier"",""type"":""int256""}],""type"":""constructor""}]";
            var byteCode =
                "0x60606040526040516020806052833950608060405251600081905550602b8060276000396000f3606060405260e060020a60003504631df4f1448114601a575b005b600054600435026060908152602090f3";
            var account = new Account(privateKey);
            var web3 = new Web3(account,uri.AbsoluteUri);
            var senderAddress = "**0xE7Fba035693dF8080f0FA30d91862EC3A9046c75**";
            var multiplier = 6;
            var transactionHash =
              await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, senderAddress, multiplier);

**Comment by juanfranblanco** [comment]
You need to add more gas, check this overload for the sample.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Tutorials/Nethereum.Tutorials/Deployment/Deployment.cs#L37

Also that one waits to get the receipt.

**Comment by srinivasvinnakota** [comment]
Thanks again juan, you helped me and your responses were very quick :)
