### ISSUE TITLE
indexed event topic caused exception on decoding ?

### ISSUE THREAD

**Issue by garyng2000** [Nethereum/Nethereum#316]
I am trying to use the event filter feature and encountered a very strange exception. the event is defined as this

event PaymentUpdate(address **indexed** sender, int32 paymentDt, int32 amt, uint8 status);

and when decoding, I would get an exception

"Index was outside the bounds of the array." and the stack trace is like this

   at Nethereum.ABI.FunctionEncoding.EventTopicDecoder.DecodeTopics[T](Object[] topics, String data)
   at Nethereum.Contracts.EventBuilder.DecodeAllEvents[T](FilterLog[] logs)
   at Nethereum.Contracts.Event.DecodeAllEvents[T](FilterLog[] logs)
   at Nethereum.Contracts.Event.<GetFilterChanges>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RO.Common3.Ethereum.<GetEventAsync>d__53`1.MoveNext() in c:\Rintagi\RO\Common3\Ethereum.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at data_Test.<>c__DisplayClass1.<<Page_Load>b__0>d__3.MoveNext() in c:\Rintagi\RO\Web\Test.aspx.cs:line 376

but if remove the 'indexed' attribute, it can be decoded properly. I didn't define any solid class for the decoding, just want a List<object>. though it still failes

**Comment by juanfranblanco** [comment]
Hi did you get sorted? Can you post your Event class? Or is this what you are referring to.

**Comment by garyng2000** [comment]
I have reviewed the source again and it seems that the only time I can decode to List<object> is when there is no indexed attribute. Otherwise, I have to make it to <T> proper. I have ended get the raw output then mimic your code to decode them into what I want as Dict<string,object>. Thanks.

**Comment by juanfranblanco** [comment]
Great that you got sorted, so your point was can I create an array of an indexed attribute? Or your point was can I decode without DTOs.

**Comment by garyng2000** [comment]
based on what I have seen, I cannot decode an eventlog item with indexed attribute(or basically topic) without a proper DTO since the internal logic use the DTO definition to map fields for indexed attributes, but I can do that for event without indexed attribute and decode them as List<object> as that is a straight generic decoding which nethereum can handle based on the abi.

**Comment by juanfranblanco** [comment]
ok got you, I need to push some code that enables that. Just needs some refactoring as it is not common use.
