### ISSUE TITLE
Method Not Found while unclock account request.

### ISSUE THREAD

**Issue by zeshanvirk** [Nethereum/Nethereum#358]
i'm trying to unlock my account using nethereum but getting this in exception 

Method not found

  at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError(RpcResponseMessage response)
   at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EtherApi.Controllers.api.EtherController.<SendTokenToAddress>d__9.MoveNext() in F:\BytePeach\EtherApi\EtherApi\Controllers\api\EtherController.cs:line 172

i'm using the following code : `      var status= await _web3.Personal.UnlockAccount.SendRequestAsync("0x9Ab1c7fA47BF64Fe2E4BDedefa6EBd4494xxxxxxx", password, 60);`

and i've also enabled personal on geth, i can get the list of accounts, newAccount etc but unable to unlock account. What i'm doing wrong?

**Comment by juanfranblanco** [comment]
The error is returned by Geth and you are passing the right parameters, nothing has changed in both sides for a long time. https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_unlockaccount

Although it is better to use a ManagedAccount. https://nethereum.readthedocs.io/en/latest/accounts/
