### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by JGdBB** [Nethereum/Nethereum#384]
I use the following function to take a order : 
```

  internal async Task<JObject> TakeOrder(Order order, BigInteger amount)
        {
            /*
             * Format of the function trade in the contract
             * trade(address tokenGet, uint amountGet, address tokenGive, uint amountGive, uint expires, uint nonce, address user, uint8 v, bytes32 r, bytes32 s, uint amount)
             */

            var funvtionInput = new object[] {
                                                 order.TokenGet,
                                                 order.AmountGet.Value,
                                                 order.TokenGive,
                                                 order.AmountGive.Value,
                                                 order.Expires,
                                                 order.Nonce,
                                                 order.User,
                                                 order.V,
                                                 order.R.HexToByteArray(),
                                                 order.S.HexToByteArray(),
                                                 amount
                                             };

            var fnTrade = EtherDeltaContract.GetFunction("trade");
            var data = fnTrade.GetData(funvtionInput);

            var gasprice = await Web3.Eth.GasPrice.SendRequestAsync();
            var txCount = await Web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(Config.User);
            var encoded = Web3.OfflineTransactionSigner.SignTransaction(Config.PrivateKey, Config.AddressEtherDelta, amount,
                                                                        txCount, gasprice.Value, Config.GasLimit, data);

            try
            {
                var txId = await Web3.Eth.Transactions.SendRawTransaction.SendRequestAsync(encoded.EnsureHexPrefix());
                var receipt = await Web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txId);
                JObject result = new JObject(new JProperty("txId", txId), new JProperty("receipt", receipt?.ToString()));
                return result;
            }
            catch (Exception e)
            {
                throw new Exception("Order has failed");
            }
        }
```

But I receive these error : 
```
{Nethereum.JsonRpc.Client.RpcResponseException: insufficient funds for gas * price + value
   at Nethereum.JsonRpc.Client.RpcClient.HandleRpcError(RpcResponse response)
   at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EtherDeltaClient.Service.<TakeOrder>d__35.MoveNext() in System.Exception {Nethereum.JsonRpc.Client.RpcResponseException}
```

But I have funds (50 $) at my wallet. I don't understand why I have this exception.
Thanks 
Jehan

**Comment by juanfranblanco** [comment]
Might be due to your gaslimit, might be due to the current gas price, you could estimate the transaction gas.

**Comment by Duanthse03268** [comment]
How can i set my gas price for transaction

**Comment by juanfranblanco** [comment]
Closing now..
