### ISSUE TITLE
Error on transaction data encoding

### ISSUE THREAD

**Issue by paveldz** [Nethereum/Nethereum#406]
Hi!

Can't encode transaction data for smart-contract method input that holds V, R, S

`contract.GetFunction("funcName").GetData("0x1c", "0xff29aa3ea57175b424c6c43a112f563f3323bc9666470f229fe20187e78f1021", "0x196037633d3370138af8fca56baf229c4d52411567ea36ebd0add89075f83d83")`

Singature of smart-contract method:
`funcName (uint8 v, bytes32 r, bytes32 s)`

Error message:
Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
Parameter name: destinationArray

Stack trace: 
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at Nethereum.ABI.Encoders.Bytes32TypeEncoder.Encode(Object value)
   at Nethereum.ABI.ABIType.Encode(Object value)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeParameters(Parameter[] parameters, Object[] values)
   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest(String sha3Signature, Parameter[] parameters, Object[] values)
   at Nethereum.Contracts.FunctionBuilder.GetData(Object[] functionInput)
   at Nethereum.Contracts.Function.GetData(Object[] functionInput)

**Comment by paveldz** [comment]
Also just tried this:

```
        public class inputDTO
        {
            [Parameter("uint8", "v", 1)]
            public string V{ get; set; }

            [Parameter("bytes32", "r", 2)]
            public string R{ get; set; }

            [Parameter("bytes32", "s", 3)]
            public string S{ get; set; }
        }
```
`contract.GetFunction("funcName").GetData(input);`

And get another error:

Message:
Invalid value for type 'Nethereum.ABI.Encoders.IntTypeEncoder': API.Ethereum.InputDTO (API.Ethereum.InputDTO )

Stack trace:
   at Nethereum.ABI.Encoders.IntTypeEncoder.Encode(Object value)
   at Nethereum.ABI.ABIType.Encode(Object value)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeParameters(Parameter[] parameters, Object[] values)
   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest(String sha3Signature, Parameter[] parameters, Object[] values)
   at Nethereum.Contracts.FunctionBuilder.GetData(Object[] functionInput)
   at Nethereum.Contracts.Function.GetData(Object[] functionInput)

**Comment by paveldz** [comment]
The issue with strings exists and I hope it will be fixed.
Workaround: explicitly convert hex string to byte array:

`contract.GetFunction("funcName").GetData("0x1c", "0xff29aa3ea57175b424c6c43a112f563f3323bc9666470f229fe20187e78f1021.HexToByteArray()", "0x196037633d3370138af8fca56baf229c4d52411567ea36ebd0add89075f83d83.HexToByteArray()")`

**Comment by juanfranblanco** [comment]
@paveldz as per Gitter conversation Nethereum does not auto encode / decode from hex. Bytes32 automatically encodes / decodes utf 8 strings due to Ethereum historical reasons as bytes32 was the only string supported. So your workaround it is actually the intended way to do it, nevertheless this might change in the future, but will break backwards compatibility so it is a major change.

**Comment by juanfranblanco** [comment]
Also there are other things to consider like endianism , etc. As bytes can be for different types, this is one of the reason to use type objects, which are now code generated as partials, giving you control of the data input creating custom properties.
