### ISSUE TITLE
TransactionReceipt.DecodeAllEvents<TransferEventDTO>() throws index out of range exception for ERC-721 transfer event.

### ISSUE THREAD

**Issue by jlholtus** [Nethereum/Nethereum#419]
I'd expect the extension method to return the actual transfer event object. But instead it throws an index out of range exception.

The cause I found is an ERC-721 token that emits transfer events with 4 topics instead of 3. It does not have data on the log entry.

An example is transaction 0xd2eeeec4d921c4f70ca6687378b5be852f221543b481e69700b2e116b6c3be34 (note: on the *rinkeby* network)

Event log for this transaction on etherscan: https://rinkeby.etherscan.io/tx/0xd2eeeec4d921c4f70ca6687378b5be852f221543b481e69700b2e116b6c3be34#eventlog

Stacktrace:

    at Nethereum.ABI.FunctionEncoding.EventTopicDecoder.DecodeTopics[T](T eventDTO, Object[] topics, String data)
    at Nethereum.ABI.FunctionEncoding.EventTopicDecoder.DecodeTopics[T](Object[] topics, String data)
    at Nethereum.Contracts.Extensions.EventExtensions.DecodeEvent[TEventDTO](EventABI eventABI, FilterLog log)
    at Nethereum.Contracts.Extensions.EventExtensions.DecodeAllEvents[TEventDTO](EventABI eventABI, FilterLog[] logs)

I'm using 3.0.0-rc1

**Comment by juanfranblanco** [comment]
@jlholtus  You need to create a specific TransferEventDTO with the 4 indexed elements for ERC-721

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/403
