### ISSUE TITLE
Exception when getting TransactionReceipt

### ISSUE THREAD

**Issue by Christ0ff** [Nethereum/Nethereum#425]
Hello, I have a simple code that gets transaction receipt by it's hash, whenever I execute it I'm getting exception
`
System.Exception : Unable to convert the result to type Nethereum.RPC.Eth.DTOs.TransactionReceipt
---- System.InvalidCastException : Unable to cast object of type 'System.Int64' to type 'System.String'.
`

My code:
`public async Task GetTransactionReceipt(string txHash)
        {
            var receipt = await web3.Eth.Transactions.GetTransactionReceipt.SendRequestAsync(txHash);
            Assert.NotNull(receipt);
        }`

The same happens when I run:
`await contract.GetFunction("myFunction").SendTransactionAndWaitForReceiptAsync(...`

**Comment by Christ0ff** [comment]
Inner exception for completeness:

Message: `Unable to cast object of type 'System.Int64' to type 'System.String'.`
Source: `Nethereum.Hex`

StackTrace:
`at Nethereum.Hex.HexTypes.HexRPCTypeJsonConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Nethereum.JsonRpc.Client.RpcMessages.RpcResponseExtensions.GetResult[T](RpcResponseMessage response, Boolean returnDefaultIfNull, JsonSerializerSettings settings)`

**Comment by juanfranblanco** [comment]
This is an issue with Ganache, which is not using a hex value, but using instead an integer. Are you using the latest version of Ganache? I believe this was solved a long time ago.

**Comment by Christ0ff** [comment]
Thanks, it worked now!!
