### ISSUE TITLE
Filtering Events - Index was outside the bounds

### ISSUE THREAD

**Issue by Christ0ff** [Nethereum/Nethereum#426]
I wish to get event logs, so I;m executing:

`[Fact]
        public async Task GetEvents()
        {
            var contract = web3.Eth.GetContract(abi, contractAddress);

            var logBidEvent = contract.GetEvent("LogBid");
            var filterInput = logBidEvent.CreateFilterInput(new BlockParameter(4), new BlockParameter(6)); // BlockParameter.CreateLatest());
            var logs = await logBidEvent.GetAllChanges<object>(filterInput);
            Assert.NotEmpty(logs);
        }`

I have tried with BlockParameter starting from 1 and the CreateLatest as second param (knowing I have 12 blocks now - looking into Ganache console)

The error is:
`System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Nethereum.ABI.FunctionEncoding.EventTopicDecoder.DecodeTopics[T](Object[] topics, String data)
   at Nethereum.Contracts.EventBuilder.DecodeAllEvents[T](FilterLog[] logs)
   at Nethereum.Contracts.Event.DecodeAllEvents[T](FilterLog[] logs)
   at Nethereum.Contracts.Event.GetAllChanges[T](NewFilterInput filterInput)
   at MarketService.Tests.ContractTest.GetEvents() in C:\Users\...\ContractTest.cs:line 111
--- End of stack trace from previous location where exception was thrown ---`

**Comment by Christ0ff** [comment]
![obraz](https://user-images.githubusercontent.com/17907519/45879359-7b8e2700-bda4-11e8-9072-78a320c03665.png)

to be sure if it is fine in the blockchain itself I run ganache in verbose mode, I can see that the logs are returned

**Comment by juanfranblanco** [comment]
Hi your event is not going to be deserialised into an object, you need to pass the EventDTO
https://github.com/Nethereum/Nethereum.Workbooks/blob/master/docs/nethereum-events-gettingstarted.workbook
