### ISSUE TITLE
Nethereum.JsonRpc.RpcClient - Error occurred when trying to send rpc requests(s)

### ISSUE THREAD

**Issue by ladinek82** [Nethereum/Nethereum#442]
Hi, 

I have tried to use your library and I have a problem. 

My code is very simple:
```
var web3 = new Web3("https://mainnet.infura.io");
var balance = web3.Eth.GetBalance.SendRequestAsync("0xB5c15851bb50b0f43F743c30dFaDf3F6F512d494").Result;
var value = Web3.Convert.FromWeiToBigDecimal(balance);
var str = value.ToString();
```
and I get a exception on SendRequestAsync. 
Here is my exception:
```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at WFA_Nethereum01.Form1.<bRefreshBalance_Click>d__1.MoveNext() in D:\Lada\Nethereum\WFA_Nethereum01\WFA_Nethereum01\Form1.cs:line 51
  InnerException: 
       HResult=-2146233088
       Message=Error occurred when trying to send rpc requests(s)
       Source=Nethereum.JsonRpc.RpcClient
       StackTrace:
            at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__12`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__8`1.MoveNext()
       InnerException: 
            HResult=-2146233088
            Message=There was an error sending request.
            Source=mscorlib
            StackTrace:
                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                 at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__17.MoveNext()
            InnerException: 
                 HResult=-2146233079
                 Message=Parent connection closed: An unexpected error occurred while sending.
                 Source=System
                 StackTrace:
                      at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
                      at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
                 InnerException: 
                      HResult=-2146232800
                      Message=Unable to read data from the transport connection: Existing connection has been forced terminated by a remote host.
                      Source=System
                      StackTrace:
                           at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
                           at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
                           at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
                      InnerException: 
                           ErrorCode=10054
                           HResult=-2147467259
                           Message=Existing connections have been forced terminated by a remote host
                           NativeErrorCode=10054
                           Source=System
                           StackTrace:
                                at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                                at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                           InnerException: 

```
I don't know where is the problem. Can you help me?

**Comment by juanfranblanco** [comment]
Hi, 

I have just seen this, what version of .net are you using? This might be a TLS issue.

**Comment by ladinek82** [comment]
Hi, 
I use version 4.6.1 and you have true. The problem was in TLS. 
Solution:
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;`

**Comment by rakesh79mca** [comment]
This is working for me
Thanks

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;

**Comment by juanfranblanco** [comment]
@anegg0  Can we put this with the Infura documentation?

**Comment by anegg0** [comment]
@juanfranblanco https://github.com/Nethereum/Nethereum.Workbooks/pull/74

**Comment by alejandrasg** [comment]
I have the same problem
I already added the line of tls, but the error persists.

Help please!

**Comment by Khay-EMMA** [comment]
Hi @alejandrasg  I'm having the same problem. Have you been able to fix the issue?

**Comment by Dave-Whiffin** [comment]
@Khay-EMMA - can you provide some more detail on your error?  Is there an inner exception?  Are you using infura?  If so are you providing an access key/project-id?

Infura introduced a requirement to pass a project id in the url.

https://infura.io/docs/gettingStarted/authentication

**Comment by juanfranblanco** [comment]
@alejandrasg @Khay-EMMA  can you post a sample ? Are you using the settings at the bottom of the docs: https://docs.nethereum.com/en/latest/Nethereum.Workbooks/docs/nethereum-gettingstarted-infura 

_Note: some communication errors can occur with INFURA if INFURA’s API and your app can’t agree on what version of TLS to use. .Net 4.5 and earlier will default to TLS v1, with TLS v1.2 deactivated if it’s included in the framework. (In .Net 4.6.*, v1.2 is the default.)_

_To enable v1.2 in 4.5.2 you can use:_

```System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12; ```

_Notice the use of |= to turn on 1.2 without affecting other protocols (that way you remain able to take advantage of future TLS versions that may become the default values in future updates to .NET)._


Or may work better for you, as per the comments:

```System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;```

**Comment by nightsoul357** [comment]
Hi,
I get a same problem.
This is my code
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            Web3 web3 = new Web3("https://mainnet.infura.io");
            var result = web3.Eth.GetBalance.SendRequestAsync("0x261c5e71eE22463b9926ac2d41a2A13aA64c3E4C").Result;
```

Here is my exception
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Error occurred when trying to send rpc requests(s))
  Source=System.Private.CoreLib
  StackTrace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ETHTest.Test.Program.Main(String[] args) in C:\Projects\Test\.Net Standard Test\ETHTest\ETHTest.Test\Program.cs:line 11

  此例外狀況原先在此呼叫堆疊擲回:
	System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
	Nethereum.JsonRpc.Client.RpcClient.SendAsync(Nethereum.JsonRpc.Client.RpcMessages.RpcRequestMessage, string)

內部例外狀況 1:
RpcClientUnknownException: Error occurred when trying to send rpc requests(s)

內部例外狀況 2:
HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
```

Looks like the same problem, but I run it on **.Net Core 3.0**.
Please Help!

**Comment by flgatormike** [comment]
I get the same error when using AWS Ethereum Preview. I am using an AWS bastion host and I can successfully access the EthExplorerURL and EthStatsURL in a browser.

But I get the error below when trying to unlockaccount:

private string url = "http://internal-cleas-loadb-1vsv7y12dj4hb-2053325910.us-east-1.elb.amazonaws.com:8545/";
private string privateKey = "0x0ADfDDa4B2a1132F82123446AcA086D7E24AA324";
var senderAddress = "0x0ADfCCa4B2a1132F8241234AcA086D7ASEEA324";
var password = "password";
var account = new Account(privateKey);
var web3 = new Web3(account, url);
var result= await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));

Error:
Error occurred when trying to send rpc requests(s) No connection could be made because the target machine actively refused it.

I am new to this so any help to set me in the right direction would be helpful.

**Comment by payplati23** [comment]
I am getting same error
       var url = "https://faucets.chain.link/kovan";

        var privateKey = "daad562540fd5ee6f5dc3a1cd95e093637b43b6951ebf7a3ab396a0faab42ef8";

        var account = new Account(privateKey);
        
        var web3 = new Web3(account, url);

        var deploymentMessage = new StandardTokenDeployment
        {
            TotalSupply = 100000
        };
      
        var deploymentHandler = web3.Eth.GetContractDeploymentHandler<StandardTokenDeployment>();
       
        var transactionReceipt = await deploymentHandler.SendRequestAndWaitForReceiptAsync(deploymentMessage);

**Comment by juanfranblanco** [comment]
The Amazon example is here, the issue was not updated https://github.com/Nethereum/Nethereum.AWS

**Comment by juanfranblanco** [comment]
@payplati23 that is a faucet (to get tokens) not the the kovan url, check infura as an example for public networks https://infura.io/docs/gettingStarted/chooseaNetwork

**Comment by payplati23** [comment]
How should I get Kovan testnetwork url?
also could you show me how to use Kovan testnetwork?
Thanks

**Comment by payplati23** [comment]
![image](https://user-images.githubusercontent.com/94351032/144805386-c211629d-8d70-4bf1-b52f-be54084a0242.png)
Can you check image?
I get ChainId Required error

**Comment by juanfranblanco** [comment]
Just add the chainId when you create the Account(privateKey, KovanChainId)

**Comment by payplati23** [comment]
What is chainId? where should I get it?

**Comment by Fabio-GitHub25** [comment]
Hello @juanfranblanco,

I have a similar problem.
I am using the telos testnet rpc https://testnet.telos.net/evm
I wrote a .NET WebApi where I used your library. Then I wanted to interact with a already deployed contract (on telos testnet).
The read function works as expected but the storing function doesn't work.
I get the following error message 
`System.AggregateException: One or more errors occurred. (Error occurred when trying to send rpc requests(s): eth_feeHistory)
 ---> Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_feeHistory
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
   --- End of inner exception stack trace ---
   at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeesAsync()
   at Nethereum.RPC.Fee1559Suggestions.TimePreferenceFeeSuggestionStrategy.SuggestFeeAsync(Nullable`1 maxPriorityFeePerGas)
   at Nethereum.RPC.TransactionManagers.TransactionManagerBase.SetTransactionFeesOrPricingAsync(TransactionInput transaction)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignTransactionRetrievingNextNonceAsync(TransactionInput transaction)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignAndSendTransactionAsync(TransactionInput transaction)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ContractApi.Controllers.SupplyChainController.StoreChainLinkEntry(AddChainLink addChainLink, String contractAddress) in /home/fabio/Projects/SupplyChain/Dashboard/ContractApi/Controllers/SupplyChainController.cs:line 91
   at lambda_method1(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:7234
User-Agent: PostmanRuntime/7.29.0
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 99
Postman-Token: 9f64954e-848c-4b0f-bd34-560bd545741b
`
My code
`var account = new Account(Constants.PRIVATE_ACCOUNT_ADDRESS, 41);
var web3 = new Web3(account, Constants.RPC_URL);
string abi = @"[abi]"
var contract = web3.Eth.GetContract(abi, contractAddress);
Task<string> function = contract.GetFunction("myFunction").SendTransactionAsync(
            account.Address,
            gas,
            value,
            new string[]{
                "My"
                "Message",
            }
        );
        function.Wait();
`

**Comment by juanfranblanco** [comment]
Ah, you need to set the web3.Eth.TransactionManager to Legacy Mode.

**Comment by Fabio-GitHub25** [comment]
> Ah, you need to set the web3.Eth.TransactionManager to Legacy Mode.

@juanfranblanco  thank you so much. Could you explain the solution again in more detail. I do not quite understand why it works now. And does the property pose a problem when I use the API in production?

**Comment by juanfranblanco** [comment]
@Fabio-GitHub25 sure what you are seeing is the default calculation of price to use 1559, so in your scenario 1559 is not supported so you need to revert to the Legacy price calculation (the old one)

**Comment by Fabio-GitHub25** [comment]
> @Fabio-GitHub25 sure what you are seeing is the default calculation of price to use 1559, so in your scenario 1559 is not supported so you need to revert to the Legacy price calculation (the old one)
> 
> eip 1559 is something specific for Ethereum that uses rpc apis that won't be implemented in Telos

Ahh ok got it. Thanks for your help :)

**Comment by juanfranblanco** [comment]
@will0225 what version of .Net are you using? What environment?

**Comment by juzer-hakimji** [comment]
Hi 
I am facing the same issue
I am using .NET 6.0. Here's my code
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
var web3 = new Web3("https://mainnet.infura.io/v3/7238211010344719ad14a89db874158c");
var balance = await web3.Eth.GetBalance.SendRequestAsync("0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae");
var etherAmount = Web3.Convert.FromWei(balance.Value);
Console.WriteLine("balance is "+etherAmount);`

Am I missing something?

**Comment by ErenTl** [comment]
> 7238211010344719ad14a89db874158c

I had the same issue. Probably the infura project id in the nethereum docs is expired. I just got a new project id from infura.io and changed it as https://mainnet.infura.io/v3/my_project_id in the code(new Web3) and it resolved. I hope this works for you too.

**Comment by ErenTl** [comment]
> Hi I am facing the same issue I am using .NET 6.0. Here's my code
> 
> ```
> System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
> var web3 = new Web3("https://mainnet.infura.io/v3/7238211010344719ad14a89db874158c");
> var balance = await web3.Eth.GetBalance.SendRequestAsync("0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae");
> var etherAmount = Web3.Convert.FromWei(balance.Value);
> Console.WriteLine("balance is "+etherAmount);
> ```
> 
> Am I missing something?

@juzer-hakimji  I had the same issue. Probably the infura project id in the nethereum docs is expired. I just got a new project id from infura.io and changed it as https://mainnet.infura.io/v3/my_project_id in the code(new Web3) and it resolved. I hope this works for you too.

**Comment by juzer-hakimji** [comment]
@ErenTl It worked Thanks :)

**Comment by juanfranblanco** [comment]
Yes @juzer-hakimji @ErenTl people were using that project id for their own purposes, so it had to be disabled. Just use your own one.

**Comment by svarogaden** [comment]
Hello.
I try to create a wallet and get a balance but get an exception :
System.AggregateException: "One or more errors occurred. (Error occurred when trying to send rpc requests(s): eth_getBalance)"

Mnemonic mnemo = new Mnemonic(Wordlist.English, WordCount.Twelve);
string backupSeed = mnemo.ToString();
 string Password = "password2";
    
var wallet = new Wallet(backupSeed, Password);
 var Account = wallet.GetAccount(0);
 var web3 = new Web3(Account);
 var balance = await web3.Eth.GetBalance.SendRequestAsync(Account.Address);

Where is the error?
