### ISSUE TITLE
DTOs have problems when function input and output are in different types

### ISSUE THREAD

**Issue by supersbbb** [Nethereum/Nethereum#47]
var GetMyFunction = contract.GetFunction<StructType>();
            var NumberIndexStruct = await GetMyFunction.CallDeserializingToObjectAsync<StructType>(index);

I have defined my struct with function parameters 
    [Nethereum.ABI.FunctionEncoding.Attributes.Function(Name = "DisplayData")]
    [Nethereum.ABI.FunctionEncoding.Attributes.FunctionOutput]

So what's the correct way to get my output as a struct when i have a single int type input?

**Comment by supersbbb** [comment]
I also tried create a new class:
[Nethereum.ABI.FunctionEncoding.Attributes.Function(Name = "DisplayData")]
    public class FunctionInput
    {
        [Nethereum.ABI.FunctionEncoding.Attributes.Parameter("uint")]
        public uint index { get; set; }
    }
and:
var id = new FunctionInput{index = 1};
var GetMyFunction = contract.GetFunction<StructType>();
 var NumberIndexStruct = await GetMyFunction.CallDeserializingToObjectAsync<StructType>(id);

Here goes the error:
"Object reference not set to an instance of an object"

   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest(String sha3Signature, String encodedParameters)
   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest[T](T functionInput)
   at Nethereum.Web3.Function`1.GetData(TFunctionInput functionInput)
   at Nethereum.Web3.Function`1.<CallDeserializingToObjectAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by juanfranblanco** [comment]
Function Input needs "at the moment" to include the encoded signature. I will be pushing a change later on today.

You can decode a class (which has all the attributes defined) with or without passing a FunctionInput

**Comment by supersbbb** [comment]
Well it is done. Thank you :)

**Comment by juanfranblanco** [comment]
The Attribute Sha3Signature has been removed now. The signature can be accessed (if required) using a deserialised abi, either by web3 or directly on the abi library
