### ISSUE TITLE
The best overloaded method match for 'Nethereum.Hex.HexTypes.HexBigInteger.HexBigInteger (string)' has some invalid arguments

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#48]
Seems that I caught a heisenbug (because it doesn't happen all the time).

This happens, at runtime (not compile time):

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded met
hod match for 'Nethereum.Hex.HexTypes.HexBigInteger.HexBigInteger(string)' has s
ome invalid arguments
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site
, T0 arg0, T1 arg1)
   at Nethereum.RPC.Eth.EthSyncing.<SendRequestAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestConsole.Program.Main(String[] args) in C:\Users\andres\documents\visua
l studio 2015\Projects\TestConsole\TestConsole\Program.cs:line 253
```

What I have around Program.cs line 253 is:

```
                    var isSyncingTask = web3.Eth.Syncing.SendRequestAsync();
                    isSyncingTask.Wait();
                    var isSyncing = isSyncingTask.Result;
```

**Comment by juanfranblanco** [comment]
We fixed at the same time ;)

**Comment by knocte** [comment]
Heh, I saw that https://github.com/Nethereum/Nethereum/commit/0ceb19a67c45bf0ffb27869c4a3021f31097b4f4 :)
