### ISSUE TITLE
[Generator] Errors out when trying to generate library with extension methods

### ISSUE THREAD

**Issue by ConnorChristie** [Nethereum/Nethereum#498]
Nethereum does not seem to be able to generate C# code for library based extension methods. If the methods are represented the same as `getListCount` then everything works, however if they are written as a strongly typed extension method, it gives the error below.

```solidity
library BytesListStorage {

    function getListCount(address a, bytes memory _key) public view returns (uint) {
        return StorageInterface(a).getUint(abi.encodePacked(_key, "count"));
    }

    function getListItem(StorageInterface s, bytes memory _key, uint _index) public view returns (bytes memory) {
        return s.getBytes(abi.encodePacked(_key, "item", _index));
    }
}
```

```
System.ArgumentException: Unknown type: StorageInterface
   at Nethereum.ABI.ABIType.CreateABIType(String typeName)
   at Nethereum.ABI.Model.Parameter..ctor(String type, String name, Int32 order, String serpentSignature)
   at Nethereum.ABI.JsonDeserialisation.ABIDeserialiser.BuildFunctionParameters(List`1 inputs)
   at Nethereum.ABI.JsonDeserialisation.ABIDeserialiser.BuildFunction(IDictionary`2 function)
   at Nethereum.ABI.JsonDeserialisation.ABIDeserialiser.DeserialiseContract(String abi)
   at Nethereum.Generators.Net.GeneratorModelABIDeserialiser.DeserialiseABI(String abi) in D:\a\1\s\src\Nethereum.Generators.Net\GeneratorModelABIDeserialiser.cs:line 13
   at Nethereum.Generator.Console.Models.ContractDefinition..ctor(String abi) in D:\a\1\s\src\Nethereum.Generator.Console\Models\ContractDefinition.cs:line 16
   at Nethereum.Generator.Console.Models.TruffleContract.GetContractConfiguration() in D:\a\1\s\src\Nethereum.Generator.Console\Models\TruffleContract.cs:line 15
   at Nethereum.Generator.Console.Configuration.GeneratorConfigurationFactory.FromTruffle(String directory, String outputFolder, String baseNamespace, CodeGenLanguage language) in D:\a\1\s\src\Nethereum.Generator.Console\Configuration\GeneratorConfigurationFactory.cs:line 114
   at Nethereum.Generator.Console.Generation.CodeGenerationWrapper.FromTruffle(String inputDirectory, String baseNamespace, String outputFolder, Boolean singleFile) in D:\a\1\s\src\Nethereum.Generator.Console\Generation\CodeGenerationWrapper.cs:line 45
   at Nethereum.Generator.Console.Commands.GenerateFromTruffleCommand.RunCommand() in D:\a\1\s\src\Nethereum.Generator.Console\Commands\GenerateFromTruffleCommand.cs:line 59
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
```

It seems like there is currently no support for accepting a contract interface as a parameter to a function whereas the generated C# code should be able to take in an address for that parameter.

**Comment by juanfranblanco** [comment]
Same as #499 although referring to the generator
