### ISSUE TITLE
eth_SendTransaction does not exist/is not avaible

### ISSUE THREAD

**Issue by aiak0s** [Nethereum/Nethereum#503]
Hello everyone,

While I'm trying to execute this code, this error comes "Nethereum.JsonRpc.Client.RpcResponseException: 'The method eth_sendTransaction does not exist/is not available"

```
Web3 web3 = new Web3("https://rinkeby.infura.io/v3/xxx");

var receipt = await web3.Eth.DeployContract.SendRequestAndWaitForReceiptAsync(Notlarabi, NotlarByte, sender2, new HexBigInteger(900000), null);
``` 

This is detailed error.
```
Nethereum.JsonRpc.Client.RpcResponseException
  HResult=0x80131500
  Message=The method eth_sendTransaction does not exist/is not available
  Source=Nethereum.JsonRpc.Client
  StackTrace:
   at Nethereum.JsonRpc.Client.ClientBase.HandleRpcError(RpcResponseMessage response)
   at Nethereum.JsonRpc.Client.ClientBase.<SendInnerRequestAsync>d__11`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nethereum.JsonRpc.Client.ClientBase.<SendInnerRequestAsync>d__12`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__8`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nethereum.RPC.TransactionReceipts.TransactionReceiptPollingService.<SendRequestAndWaitForReceiptAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nethereum.RPC.TransactionReceipts.TransactionReceiptPollingService.<DeployContractAndWaitForReceiptAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dene.Program.<Main>d__0.MoveNext() in C:\Users\nevyo\source\repos\Dene\Dene\Program.cs:line 39
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dene.Program.<Main>(String[] args)

```

**Comment by juanfranblanco** [comment]
Yes, you cannot use SendTransaction with Infura as you need to sign your transactions before hand. Use with an Account object for this providing your private key to send raw transactions.

https://nethereum.readthedocs.io/en/latest/accounts/ this describes it with detail

**Comment by juanfranblanco** [comment]
In simple terms:

```csharp
var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
var account = new Account(privateKey);
var web3 = new Web3("url", account);
```
