### ISSUE TITLE
Exception: Newtonsoft.Json.JsonSerializationException: Required property 'id' not found in JSON. Path ''

### ISSUE THREAD

**Issue by alexbrks** [Nethereum/Nethereum#543]
Hi, when trying to call SendTransactionAsync I get this exception:
```
JsonRpcSharp.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> Newtonsoft.Json.JsonSerializationException: Required property 'id' not found in JSON. Path '', line 1, position 72.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at JsonRpcSharp.Client.RpcClient.SendAsync(RpcRequestMessage request, String route, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at JsonRpcSharp.Client.RpcClient.SendAsync(RpcRequestMessage request, String route, CancellationToken cancellationToken)
   at JsonRpcSharp.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route, CancellationToken cancellationToken)
   at JsonRpcSharp.Client.ClientBase.SendInnerRequestAsync[T](RpcRequest request, String route, CancellationToken cancellationToken)
   at JsonRpcSharp.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route, CancellationToken cancellationToken)
   at Nethereum.RPC.TransactionManagers.TransactionManagerBase.GetGasPriceAsync(TransactionInput transactionInput, CancellationToken cancellationToken)
   at Nethereum.Web3.Accounts.Managed.ManagedAccountTransactionManager.SendTransactionAsync(TransactionInput transactionInput, CancellationToken cancellationToken)
```

This is the code from the class were the exception happens, the ABI and bytecode are included.
```
public class EthereumService : IEthereumService
    {
        private Web3 _web3;
        private const string ABI = @"[ { 'constant': true, 'inputs': [ { 'name': '', 'type': 'uint256' }, { 'name': '', 'type': 'uint256' } ], 'name': 'parentLots', 'outputs': [ { 'name': '', 'type': 'uint256' }, { 'name': 'producer', 'type': 'string' }, { 'name': 'processStage', 'type': 'string' }, { 'name': 'quantity', 'type': 'int256' }, { 'name': 'lotnumber', 'type': 'int256' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0x066ed012' }, { 'constant': true, 'inputs': [ { 'name': '', 'type': 'uint256' }, { 'name': '', 'type': 'uint256' }, { 'name': 'quantity', 'type': 'int256' }, { 'name': 'lotnumber', 'type': 'int256' } ], 'name': 'childLots', 'outputs': [ { 'name': '', 'type': 'uint256' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0x9a59e78c' }, { 'constant': true, 'inputs': [ { 'name': '', 'type': 'uint256' }, { 'name': '', 'type': 'uint256' } ], 'name': 'quantityChanges', 'outputs': [ { 'name': '', 'type': 'uint256' }, { 'name': 'producer', 'type': 'string' }, { 'name': 'processStage', 'type': 'string' }, { 'name': 'quantity', 'type': 'int256' }, { 'name': 'lotnumber', 'type': 'int256' }, { 'name': 'content', 'type': 'string' }, { 'name': 'active', 'type': 'bool' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0x1587026d' }, { 'constant': true, 'inputs': [ { 'name': '', 'type': 'uint256' }, { 'name': '', 'type': 'uint256' }, { 'name': 'quantity', 'type': 'int256' }, { 'name': 'lotnumber', 'type': 'int256' }, { 'name': 'content', 'type': 'string' } ], 'name': 'stages', 'outputs': [ { 'name': '', 'type': 'string' }, { 'name': 'producer', 'type': 'string' }, { 'name': 'processStage', 'type': 'string' }, { 'name': 'quantity', 'type': 'uint256' }, { 'name': 'lotnumber', 'type': 'int256' }, { 'name': 'content', 'type': 'string' }, { 'name': 'active', 'type': 'bool' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0x472ab4fe' }, { 'constant': true, 'inputs': [ { 'name': '', 'type': 'uint256' }, { 'name': '_processStage', 'type': 'string' }, { 'name': '_quantity', 'type': 'uint256' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' } ], 'name': 'lots', 'outputs': [ { 'name': 'lotID', 'type': 'uint256' }, { 'name': 'producer', 'type': 'string' }, { 'name': 'processStage', 'type': 'string' }, { 'name': 'quantity', 'type': 'uint256' }, { 'name': 'lotnumber', 'type': 'int256' }, { 'name': 'content', 'type': 'string' }, { 'name': 'active', 'type': 'bool' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0x5abe18c4' }, { 'constant': false, 'inputs': [ { 'name': '_producer', 'type': 'string' }, { 'name': '_processStage', 'type': 'string' }, { 'name': '_quantity', 'type': 'uint256' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' } ], 'name': 'StoreLot', 'outputs': [ { 'name': 'success', 'type': 'bool' } ], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0xaed8f688' }, { 'constant': false, 'inputs': [ { 'name': '_lotID', 'type': 'uint256' }, { 'name': '_quantity', 'type': 'uint256' } ], 'name': 'DeleteLot', 'outputs': [], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0x2d96591e' }, { 'constant': false, 'inputs': [ { 'name': '_lotID', 'type': 'uint256' }, { 'name': '_quantity', 'type': 'uint256' }, { 'name': '_processStage', 'type': 'string' }, { 'name': '_quantity', 'type': 'uint256' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' } ], 'name': 'ChangeQuantity', 'outputs': [], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0x88d95b63' }, { 'constant': false, 'inputs': [ { 'name': '_lotID', 'type': 'uint256' }, { 'name': '_processStage', 'type': 'string' } ], 'name': 'ChangeStage', 'outputs': [], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0x2b83d053' }, { 'constant': false, 'inputs': [ { 'name': '_lotID', 'type': 'uint256' }, { 'name': '_producer', 'type': 'string' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' } ], 'name': 'ModifyLot', 'outputs': [], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0x180d2292' }, { 'constant': false, 'inputs': [ { 'name': '_lotIDs', 'type': 'uint256[]' }, { 'name': '_quantities', 'type': 'uint256[]' }, { 'name': '_producer', 'type': 'string' }, { 'name': '_processStage', 'type': 'string' }, { 'name': '_quantity', 'type': 'uint256' }, { 'name': '_lotnumber', 'type': 'int256' }, { 'name': '_content', 'type': 'string' } ], 'name': 'LotMerger', 'outputs': [], 'payable': false, 'stateMutability': 'nonpayable', 'type': 'function', 'signature': '0x39075356' }, { 'constant': true, 'inputs': [], 'name': 'GetLotcounter', 'outputs': [ { 'name': '_lotCounter', 'type': 'uint256' } ], 'payable': false, 'stateMutability': 'view', 'type': 'function', 'signature': '0xc4373abb' } ]";
        private readonly string byteCode = "0x60806040526000805534801561001457600080fd5b50611889806100246000396000f3fe6080604052600436106100ba576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063066ed012146100bf57806309dfed99146101185780631587026d146101715780632b83d053146101ca578063390753561461029c5780633966716e146105ce5780636e9e53a114610613578063914a51b114610786578063921c67b4146107c1578063aed8f6881461087f578063c4373abb14610aa1578063f1648e8414610acc575b600080fd5b3480156100cb57600080fd5b50610102600480360360408110156100e257600080fd5b810190808035906020019092919080359060200190929190505050610c78565b6040518082815260200191505060405180910390f35b34801561012457600080fd5b5061015b6004803603604081101561013b57600080fd5b810190808035906020019092919080359060200190929190505050610ca8565b6040518082815260200191505060405180910390f35b34801561017d57600080fd5b506101b46004803603604081101561019457600080fd5b810190808035906020019092919080359060200190929190505050610cd8565b6040518082815260200191505060405180910390f35b3480156101d657600080fd5b5061029a600480360360408110156101ed57600080fd5b81019080803590602001909291908035906020019064010000000081111561021457600080fd5b82018360208201111561022657600080fd5b8035906020019184600183028401116401000000008311171561024857600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610d08565b005b3480156102a857600080fd5b506105cc600480360360e08110156102bf57600080fd5b81019080803590602001906401000000008111156102dc57600080fd5b8201836020820111156102ee57600080fd5b8035906020019184602083028401116401000000008311171561031057600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561037057600080fd5b82018360208201111561038257600080fd5b803590602001918460208302840111640100000000831117156103a457600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561040457600080fd5b82018360208201111561041657600080fd5b8035906020019184600183028401116401000000008311171561043857600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561049b57600080fd5b8201836020820111156104ad57600080fd5b803590602001918460018302840111640100000000831117156104cf57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929080359060200190929190803590602001909291908035906020019064010000000081111561054657600080fd5b82018360208201111561055857600080fd5b8035906020019184600183028401116401000000008311171561057a57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610e92565b005b3480156105da57600080fd5b50610611600480360360408110156105f157600080fd5b810190808035906020019092919080359060200190929190505050610f56565b005b34801561061f57600080fd5b506107846004803603608081101561063657600080fd5b81019080803590602001909291908035906020019064010000000081111561065d57600080fd5b82018360208201111561066f57600080fd5b8035906020019184600183028401116401000000008311171561069157600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929080359060200190929190803590602001906401000000008111156106fe57600080fd5b82018360208201111561071057600080fd5b8035906020019184600183028401116401000000008311171561073257600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290505050610ffb565b005b34801561079257600080fd5b506107bf600480360360208110156107a957600080fd5b8101908080359060200190929190505050611072565b005b3480156107cd57600080fd5b50610804600480360360408110156107e457600080fd5b8101908080359060200190929190803590602001909291905050506110a4565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610844578082015181840152602081019050610829565b50505050905090810190601f1680156108715780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561088b57600080fd5b50610a87600480360360a08110156108a257600080fd5b81019080803590602001906401000000008111156108bf57600080fd5b8201836020820111156108d157600080fd5b803590602001918460018302840111640100000000831117156108f357600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561095657600080fd5b82018360208201111561096857600080fd5b8035906020019184600183028401116401000000008311171561098a57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f820116905080830192505050505050509192919290803590602001909291908035906020019092919080359060200190640100000000811115610a0157600080fd5b820183602082011115610a1357600080fd5b80359060200191846001830284011164010000000083111715610a3557600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600081840152601f19601f82011690508083019250505050505050919291929050505061116c565b604051808215151515815260200191505060405180910390f35b348015610aad57600080fd5b50610ab661130e565b6040518082815260200191505060405180910390f35b348015610ad857600080fd5b50610b0560048036036020811015610aef57600080fd5b8101908080359060200190929190505050611317565b604051808881526020018060200180602001878152602001868152602001806020018515151515815260200184810384528a818151815260200191508051906020019080838360005b83811015610b69578082015181840152602081019050610b4e565b50505050905090810190601f168015610b965780820380516001836020036101000a031916815260200191505b50848103835289818151815260200191508051906020019080838360005b83811015610bcf578082015181840152602081019050610bb4565b50505050905090810190601f168015610bfc5780820380516001836020036101000a031916815260200191505b50848103825286818151815260200191508051906020019080838360005b83811015610c35578082015181840152602081019050610c1a565b50505050905090810190601f168015610c625780820380516001836020036101000a031916815260200191505b509a505050505050505050505060405180910390f35b600260205281600052604060002081815481101515610c9357fe5b90600052602060002001600091509150505481565b600360205281600052604060002081815481101515610cc357fe5b90600052602060002001600091509150505481565b600460205281600052604060002081815481101515610cf357fe5b90600052602060002001600091509150505481565b806040516020018082805190602001908083835b602083101515610d415780518252602082019150602081019050602083039250610d1c565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405160208183030381529060405280519060200120600160008481526020019081526020016000206002016040516020018082805460018160011615610100020316600290048015610df05780601f10610dce576101008083540402835291820191610df0565b820191906000526020600020905b815481529060010190602001808311610ddc575b505091505060405160208183030381529060405280519060200120141515610e8e5780600160008481526020019081526020016000206002019080519060200190610e3c9291906116f8565b5060056000838152602001908152602001600020819080600181540180825580915050906001820390600052602060002001600090919290919091509080519060200190610e8b9291906116f8565b50505b5050565b6000610ea1868686868661152e565b905060008090505b8851811015610f4b57600260008381526020019081526020016000208982815181101515610ed357fe5b906020019060200201519080600181540180825580915050906001820390600052602060002001600090919290919091505550610f3e8982815181101515610f1757fe5b906020019060200201518983815181101515610f2f57fe5b906020019060200201516116cc565b8080600101915050610ea9565b505050505050505050565b806001600084815260200190815260200160002060030154141515610ff75780600160008481526020019081526020016000206003018190555060046000838152602001908152602001600020819080600181540180825580915050906001820390600052602060002001600090919290919091505550600060016000848152602001908152602001600020600301541415610ff657610ff582611072565b5b5b5050565b826001600086815260200190815260200160002060010190805190602001906110259291906116f8565b508160016000868152602001908152602001600020600401819055508060016000868152602001908152602001600020600501908051906020019061106b9291906116f8565b5050505050565b60006001600083815260200190815260200160002060060160006101000a81548160ff02191690831515021790555050565b6005602052816000526040600020818154811015156110bf57fe5b90600052602060002001600091509150508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156111645780601f1061113957610100808354040283529160200191611164565b820191906000526020600020905b81548152906001019060200180831161114757829003601f168201915b505050505081565b600080600054905061117c611778565b60e06040519081016040528083815260200189815260200188815260200187815260200186815260200185815260200160011515815250905060046000838152602001908152602001600020869080600181540180825580915050906001820390600052602060002001600090919290919091505550600560008381526020019081526020016000208790806001815401808255809150509060018203906000526020600020016000909192909190915090805190602001906112409291906116f8565b5050806001600084815260200190815260200160002060008201518160000155602082015181600101908051906020019061127c9291906117b8565b5060408201518160020190805190602001906112999291906117b8565b50606082015181600301556080820151816004015560a08201518160050190805190602001906112ca9291906117b8565b5060c08201518160060160006101000a81548160ff021916908315150217905550905050600080815480929190600101919050555060019250505095945050505050565b60008054905090565b6001602052806000526040600020600091509050806000015490806001018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156113c95780601f1061139e576101008083540402835291602001916113c9565b820191906000526020600020905b8154815290600101906020018083116113ac57829003601f168201915b505050505090806002018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156114675780601f1061143c57610100808354040283529160200191611467565b820191906000526020600020905b81548152906001019060200180831161144a57829003601f168201915b505050505090806003015490806004015490806005018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156115115780601f106114e657610100808354040283529160200191611511565b820191906000526020600020905b8154815290600101906020018083116114f457829003601f168201915b5050505050908060060160009054906101000a900460ff16905087565b60008054905061153c611778565b60e06040519081016040528083815260200188815260200187815260200186815260200185815260200184815260200160011515815250905060046000838152602001908152602001600020859080600181540180825580915050906001820390600052602060002001600090919290919091505550600560008381526020019081526020016000208690806001815401808255809150509060018203906000526020600020016000909192909190915090805190602001906116009291906116f8565b5050806001600084815260200190815260200160002060008201518160000155602082015181600101908051906020019061163c9291906117b8565b5060408201518160020190805190602001906116599291906117b8565b50606082015181600301556080820151816004015560a082015181600501908051906020019061168a9291906117b8565b5060c08201518160060160006101000a81548160ff02191690831515021790555090505060008081548092919060010191905055508191505095945050505050565b60008160016000858152602001908152602001600020600301540390506116f38382610f56565b505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061173957805160ff1916838001178555611767565b82800160010185558215611767579182015b8281111561176657825182559160200191906001019061174b565b5b5090506117749190611838565b5090565b60e0604051908101604052806000815260200160608152602001606081526020016000815260200160008152602001606081526020016000151581525090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106117f957805160ff1916838001178555611827565b82800160010185558215611827579182015b8281111561182657825182559160200191906001019061180b565b5b5090506118349190611838565b5090565b61185a91905b8082111561185657600081600090555060010161183e565b5090565b9056fea165627a7a72305820a8264171da19a8f5bb33ab5572eea43739edd8dbe4dc4a371e1218cd64c0b4300029";
        private const string contractAddress = "0xD0828aEB00e4db6813e2f330318Ef94D2BbA2f60";
        private const string senderAddress = "0x12890d2cce102216644c59daE5baed380d84830c";
        private const string password = "password";
        public EthereumService()
        {
            var account = new ManagedAccount(senderAddress, password);
            _web3 = new Web3(account, "http://localhost:8545");
        }
        public async Task<decimal> GetBalance(string walletAddress)
        {
            var balance = await _web3.Eth.GetBalance.SendRequestAsync(walletAddress);
            return Web3.Convert.FromWei(balance.Value, 18);
        }

        public async Task<string> StoreLot(LotDTO lot)
        {
            var contract = _web3.Eth.GetContract(ABI, contractAddress);
            var storeLotFunction = contract.GetFunction("StoreLot");
            return await storeLotFunction.SendTransactionAsync(senderAddress, new HexBigInteger(900000), null, lot.producer, lot.processStage, lot.quantity, lot.lotnumber, lot.content);
        }

        public async Task<uint> GetLotCounter()
        {
            var contract = _web3.Eth.GetContract(ABI, contractAddress);
            var getCounterFunction = contract.GetFunction("GetLotcounter");
            return await getCounterFunction.CallAsync<uint>();
        }
    }
```

I'm using the clique blockchain provided here: https://github.com/Nethereum/Nethereum/tree/master/testchain/clique
with this .bat for start
```
RD /S /Q %~dp0\devChain\geth
geth  --datadir=devChain init genesis_clique.json
geth --nodiscover --rpc --datadir=devChain  --rpccorsdomain "*" --mine --rpcapi "eth,web3,personal,net,miner,admin,debug" --rpcaddr "0.0.0.0" --unlock 0x12890d2cce102216644c59daE5baed380d84830c --password "pass.txt"  
```

This only happens with SendTransactionAsync, CallAsync works.

**Comment by juanfranblanco** [comment]
@alexbrks  can you tell me what version of Nethereum you are using and Nuget?

**Comment by alexbrks** [comment]
@juanfranblanco 
```
"Nethereum/0.0.2.60": {
        "dependencies": {
          "JsonRpcSharp": "0.9.54733"
        },
        "runtime": {
          "lib/netstandard2.0/Nethereum.ABI.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Accounts.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Contracts.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Hex.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.KeyStore.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.RLP.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.RPC.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Signer.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.StandardTokenEIP20.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Util.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          },
          "lib/netstandard2.0/Nethereum.Web3.dll": {
            "assemblyVersion": "3.0.0.0",
            "fileVersion": "3.0.0.0"
          }
        }
```
```
"NuGet.Frameworks/4.7.0": {
        "dependencies": {
          "NETStandard.Library": "2.0.3"
        },
        "runtime": {
          "lib/netstandard1.6/NuGet.Frameworks.dll": {
            "assemblyVersion": "4.7.0.5",
            "fileVersion": "4.7.0.5148"
          }
        },
        "compile": {
          "lib/netstandard1.6/NuGet.Frameworks.dll": {}
        }
      }
```

**Comment by alexbrks** [comment]
@juanfranblanco I tried doing the same operation with Ganache-CLI, left everything the same but the contract address and sender address and it worked fine, so it must be something with the transaction for the Geth client. As I said before I used the clique test-chain provided, the only thing I've changed is the startup.bat

**Comment by juanfranblanco** [comment]
You are using the wrong Nethereum package. Please use Nethereum.Web3 @knocte this is causing confusion.
