### ISSUE TITLE
Get Nethereum.JsonRpc.Client.RpcClientTimeoutException when JSON RPC payload size is mulitplies of 512

### ISSUE THREAD

**Issue by adamzhangsm** [Nethereum/Nethereum#601]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

## Current Behavior
When the JSON RPC payload size return from Ethereum is mulitplies of 512, we will get this exception below.

`
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to web socket requests(s) ---> Nethereum.JsonRpc.Client.RpcClientTimeoutException: Rpc timeout after 20000 milliseconds ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.         Private[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Nethereum.JsonRpc.WebSocketClient.WebSocketClient.ReceiveBufferedResponseAsync(ClientWebSocket client, Byte[] buffer)
   --- End of inner exception stack trace ---
   at Nethereum.JsonRpc.WebSocketClient.WebSocketClient.ReceiveBufferedResponseAsync(ClientWebSocket client, Byte[] buffer)
   at Nethereum.JsonRpc.WebSocketClient.WebSocketClient.ReceiveFullResponseAsync(ClientWebSocket client)
   at Nethereum.JsonRpc.WebSocketClient.WebSocketClient.SendAsync(RpcRequestMessage request, String route)
   --- End of inner exception stack trace ---
   at Nethereum.JsonRpc.WebSocketClient.WebSocketClient.SendAsync(RpcRequestMessage request, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequest request, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
`

We suspect this code will make additional read call which cause this RpcClientTimeoutException  eventually.  The variable  bytesRead will be 512 in this situation.

https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.JsonRpc.WebSocketClient/WebSocketClient.cs

                if (lastByte == 10 || bytesRead < 512)  //return signalled with a line feed / or just less than the full message
                {
                    bytesRead = 0;
                }
                else
                {
                    bytesRead = await ReceiveBufferedResponseAsync(client, buffer).ConfigureAwait(false);
                }

## Possible Solution
WebSocketReceiveResult.EndOfMessage can help us to check if the message is well received or we shall take additional read call to get left message from server. 
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketreceiveresult.endofmessage?view=netframework-4.8#System_Net_WebSockets_WebSocketReceiveResult_EndOfMessage

We can make ReceiveBufferedResponseAsync to return WebSocketReceiveResult object directly. 

            do
            {
                receiveResult = await ReceiveBufferedResponseAsync(client, buffer).ConfigureAwait(false);
                if (receiveResult.Count > 0)
                {
                    memoryStream.Write(buffer, 0, receiveResult.Count);
                }

            } while (receiveResult.EndOfMessage == false);

**Comment by juanfranblanco** [comment]
Hi @adamzhangsm what client are you using? Parity and Geth do not provide EndOfMessage they actually throw an exception if it is used. Also they need to use the terminator 10.

**Comment by adamzhangsm** [comment]
The server side is Azure Blockchain Service (ABS) which is based on Quorum 2.2.3.
WebSocket can have this EndOfMessage from ABS.

**Comment by juanfranblanco** [comment]
Thanks @adamzhangsm I think I may need to do another flavour of Websockets as this is not the standard. I guess it is proxied in a different way.

**Comment by juanfranblanco** [comment]
Can you use http whilst I think the best way to support both worlds.

**Comment by NovichikhinAlexey** [comment]
@juanfranblanco Hello.
Do you plan to make a release with your fix? 
We use Nethereum with Azure Blockchain Service (ABS) and we face issue base on this bug. will be greate to have this fix soon as possible.

P.S. We checked the local code of the library and we can confirm what this fix will solve the problem. need only release Nuget.

**Comment by NovichikhinAlexey** [comment]
look like you have an issue with CI pipeline
https://dev.azure.com/nethereumproject/Nethereum/_build/results?buildId=603&view=logs

**Comment by juanfranblanco** [comment]
@NovichikhinAlexey thanks for checking it out. Yeah pipeline is broken.. I am targetting Monday now for release. Might need to a post of release of the Blazor Metamask if not ready by then.

**Comment by juanfranblanco** [comment]
@NovichikhinAlexey @adamzhangsm CI packages https://www.myget.org/feed/nethereum/package/nuget/Nethereum.Web3

**Comment by juanfranblanco** [comment]
This is released now, thanks!
