### ISSUE TITLE
Error connecting to AWS Ethereum Preview

### ISSUE THREAD

**Issue by flgatormike** [Nethereum/Nethereum#659]
I posted this in another closed issue, but not sure if I should create a new one instead.

I get the error below when trying to connect to AWS Ethereum Preview. I am using an AWS bastion host and I can successfully access the EthExplorerURL and EthStatsURL in a browser.

But I get the error below when trying to unlockaccount:

private string url = "http://internal-cleas-loadb-1vsv7y12dj4hb-2053325910.us-east-1.elb.amazonaws.com:8545/";
private string privateKey = "0x0ADfDDa4B2a1132F82123446AcA086D7E24AA324";
var senderAddress = "0x0ADfCCa4B2a1132F8241234AcA086D7ASEEA324";
var password = "password";
var account = new Account(privateKey);
var web3 = new Web3(account, url);
var result= await web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, new HexBigInteger(120));

Error:
Error occurred when trying to send rpc requests(s) No connection could be made because the target machine actively refused it.

I am new to this so any help to set me in the right direction would be helpful.

**Comment by flgatormike** [comment]
Here is the stacktrace:

   at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendInnerRequestAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendInnerRequestAsync>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__8`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Clearup.Web.Areas.Api.Controllers.EthereumController.<TestContract>d__14.MoveNext() in C:\_Projects\clearup.web\Clearup.Web\Areas\Api\Controllers\EthereumController.cs:line 92

**Comment by flgatormike** [comment]
Sorry, I wasn't setting the URL properly. Now that I set it properly, I get this error:

Rpc timeout after 20000 milliseconds

**Comment by juanfranblanco** [comment]
@flgatormike Hi!!, first thing, if you are using your private key to sign messages you do not need to unlock your account.
Can you try another method like GetBlockNumber?

Something like this?

http://playground.nethereum.com/csharp/id/1002

**Comment by flgatormike** [comment]
When I call GetBlockNumber using my AWS Ethereum URL, I get this error:
Rpc timeout after 20000 milliseconds The operation was canceled.

When I run it using the URL in the link you provided, it works and I get "{11654873}"

My AWS URL is in this format with the port:
http://internal-clear-LoadB-12V6U823I11OC-802325232.us-east-1.elb.amazonaws.com:8545

I am using an Amazon Bastion Host to connect and I am able to open this in a browser successfully and see it is running:
http://internal-clear-loadb-10v6u823i11oc-828732237.us-east-1.elb.amazonaws.com:8080

Any ideas what I might be doing wrong? I am just learning and am spending a couple hours a day playing around but I got stuck here.

**Comment by juanfranblanco** [comment]
Ok so obviously you are exposing your public urls as per here. https://docs.aws.amazon.com/blockchain-templates/latest/developerguide/blockchain-templates-ethereum.html

Have you done a curl to validate you can access them?

**Comment by flgatormike** [comment]
Thanks, I must have missed that a network ID between 1 and 4 specifies a public network. I just tried an ID of 1 and also 1234, and still get a timeout for both. I tried curl and also get a timeout for both.

It doesn't make sense since I am able to access the explorer url (port 8080) in my browser when I connect with ssh tunnel. It is obviously not an issue with nethereum so you should probably close this issue. I'll have to just try some different things with my aws security settings. What a pain this is.

Thanks!!!

**Comment by juanfranblanco** [comment]
Hopefully you get sorted soon
