### ISSUE TITLE
the method personal_importRawKey does not exist/is not available

### ISSUE THREAD

**Issue by lss110521** [Nethereum/Nethereum#660]
var Web3 = require('web3');
var web3 = new Web3('https://http-testnet.hecochain.com');
 var accountAdd = await web3.eth.personal.importRawKey("cd3376bb711cb332ee3fb2ca04c6a8b9f70c316fcdf7a1f44ef4c7999483295e", "password1234");
console.log(accountAdd);

//error
(node:11311) UnhandledPromiseRejectionWarning: Error: Returned error: the method personal_newAccount does not exist/is not available
    at Object.ErrorResponse (/root/eth/web3_1version/node_modules/_web3-core-helpers@1.3.3@web3-core-helpers/lib/errors.js:28:19)
    at /root/eth/web3_1version/node_modules/_web3-core-requestmanager@1.3.3@web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/root/eth/web3_1version/node_modules/_web3-providers-http@1.3.3@web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/eth/web3_1version/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/root/eth/web3_1version/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/root/eth/web3_1version/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/root/eth/web3_1version/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by juanfranblanco** [comment]
You need to use new Account("privateKey")
