### ISSUE TITLE
Error using StreamingWebSocketClient 

### ISSUE THREAD

**Issue by shargon** [Nethereum/Nethereum#662]
## Current Behavior
`   at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.HandleIncomingMessagesAsync()`

![image](https://user-images.githubusercontent.com/3167973/110463045-b64dbc00-80d1-11eb-8bac-809e5ee553f0.png)

## Steps to Reproduce
1. Use `StreamingWebSocketClient` with the last vesion of parity
2. Wait some time
3. Exception appears

## Code

```csharp
var subscribed = true;
using var ws = new StreamingWebSocketClient(cfg.Url, log: LogManager.GetLogger<Program>());
var subscription = new ParityPubSubObservableSubscription<Transaction[]>(ws);

subscription.GetSubscribeResponseAsObservable().Subscribe(subscriptionId => Console.WriteLine("Subscription Id: " + subscriptionId));

subscription.GetUnsubscribeResponseAsObservable().Subscribe(response => subscribed = false);

await ws.StartAsync();
var cache = new HashSet<string>();

subscription.GetSubscriptionDataResponsesAsObservable().Subscribe(async txs => await TestTx(txs.Where(u => cache.Add(u.TransactionHash)));

var request = new RpcRequest(1, "parity_allTransactions", Array.Empty<object>());
await subscription.SubscribeAsync(request);
```

**Comment by shargon** [comment]
More verbosity log
```
2021-03-09 15:45:56 [ERROR] log - RPC Exception, RPC Request: RPC Response: 
=======================================================(inner most exception)===
 (1) Nethereum.JsonRpc.Client.RpcResponseException
================================================================================

Message:
"Client connection error"

Properties:
  RpcError.RpcError = "Nethereum.JsonRpc.Client.RpcError"

Stack Trace:
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServices.cs:line 14
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 60
   at System.Reactive.Sink`2.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:line 96
   at System.Reactive.Subjects.Subject`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 124
   at Nethereum.RPC.Reactive.RpcStreaming.RpcStreamingSubscriptionObservableHandler`1.HandleDataResponseError(RpcResponseException exception)
   at Nethereum.JsonRpc.Client.Streaming.RpcStreamingSubscriptionHandler`1.HandleClientError(Exception ex)
   at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.HandleError(Exception exception)
   at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.ReceiveBufferedResponseAsync(ClientWebSocket client, Byte[] buffer)
   at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.ReceiveFullResponseAsync(ClientWebSocket client)
   at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.HandleIncomingMessagesAsync()
================================================================================

Exception thrown: 'System.NullReferenceException' in Nethereum.JsonRpc.WebSocketClient.dll
Object reference not set to an instance of an object.
```

**Comment by shargon** [comment]
> Thanks, Ill try to reproduce it today.

I think that it's a kind of timeout

**Comment by xx5ll** [comment]
any update?

**Comment by xx5ll** [comment]
it seem like `ForceCompleteReadTotalMilliseconds` is 100000ms by default, if you use a filter to Subscribe and do not receive anything in 100s, you will get `Client connection error`. 
you can set `StreamingWebSocketClient.ForceCompleteReadTotalMilliseconds` or `WebSocketClient.ForceCompleteReadTotalMilliseconds`

**Comment by juanfranblanco** [comment]
Yes I forgot to update this, this is the normal timeout behaviour, one fast for connections, and the second is much longer to allow the continuous reading.

**Comment by SnakePin** [comment]
Possibly closed by the #734 ? Doesn't fix the actual timeout but it should fix the NullReferenceException.
