### ISSUE TITLE
Getting an ambiguous exception Can not convert Object to String.

### ISSUE THREAD

**Issue by JasonWHowse** [Nethereum/Nethereum#745]
This issue seems similar to "Error on parsing rpc response to BlockWithTransactions from geth 1.9.0 #573"
https://github.com/Nethereum/Nethereum/issues/573

I am using the following code

        public async Task GetHashFromContract() {
            Contract cont = this.GetContract();
            object[] parameters = new object[] { this.account.Address };
            Function getFunct = cont.GetFunction("balanceOf");
            string output = (await getFunct.CallAsync<int>(parameters)).ToString();//returns the expected value
            Log.InfoLog(output);
            getFunct = cont.GetFunction("ownerOf");Log.InfoLog("ln123");
            parameters = new object[] { new BigInteger(new HexBigInteger("0x9dfa6381a7a4c9d157cb152ba58e07107cc387932249cb4c45a7869014fa4a20")) }; Log.InfoLog("ln124");parameters = new object[] { "0x9dfa6381a7a4c9d157cb152ba58e07107cc387932249cb4c45a7869014fa4a20" };//passing the wrong values
            try {
                output = (await getFunct.CallAsync<Newtonsoft.Json.Linq.JToken>(parameters)).ToString();
                Log.InfoLog(output);
            } catch(Exception e) {
                Log.InfoLog("ln124");
                Log.ErrorLog(e);
                Log.ErrorLog(e.GetType().ToString());
            }
        }

When using the most recent version of NUGET package Nethereum.Contracts, 4.1.1, Nethereum.Hex, 4.1.1, Nethereum.Web3 4.1.1 and was getting the following error I'll post the stack trace at the bottom of the issue.  
Exception 1: Can not convert Object to String. Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Nethereum.Contracts.ContractCall.CallAsync(CallInput callInput, BlockParameter block)
   at Nethereum.Contracts.FunctionBase.CallAsync[TReturn](CallInput callInput)
   at iNFT.src.Ethereum_Interact.GetHashFromContract() in

When I changed the versions to NUGET package Nethereum.Contracts 4.0.5, Nethereum.Hex 4.1.1, Nethereum.Web3 4.0.5 I get an expected exception for passing bad values to the contract. (VM Exception while processing transaction) don't worry about this.

**Comment by juanfranblanco** [comment]
```await getFunct.CallAsync<Newtonsoft.Json.Linq.JToken>(parameters)).ToString()```
You cannot use a JToken you need to use a string.

**Comment by JasonWHowse** [comment]
I was using JToken in this instance to try to push it through after trying a bunch of other stuff such as string, object, int, and a few other things that I can't remember, changing what was entered into the template didn't change the exception.  I was throwing things up and seeing if anything would stuck and JToken was the last thing I tried because of the exception stacktrace.  I reverted to the 4.0.5 versions of the Contracts and Web3 packages and it seems to work fine and I am now getting the expected response from the ownerof method.

Adding to this issue note I am currently using the following NuGet packages (as well as the aforementioned packages) because the exception does seem like it may be effected by one the following:
IPFS.Http.Client 0.33.0
Mime (by red) 3.2.3
Newtonsoft.Json 13.0.1
xunit.assert 2.4.1



Just ran a test on web3/contracts 4.1.1;

```
string tempAddress = (await this.GetContract().GetFunction(
                    "ownerOf").CallAsync<object>(new object[] { index })).ToString();
```

I am still getting the results as before:
 
ERROR - 11/27/2021 9:58:26 AM: Can not convert Object to String.
ERROR - 11/27/2021 9:58:26 AM:    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Nethereum.Contracts.ContractCall.CallAsync(CallInput callInput, BlockParameter block)
   at Nethereum.Contracts.FunctionBase.CallAsync[TReturn](CallInput callInput)
   at iNFT.src.Ethereum_Interact.TokenList() in 

Swapping template to string:
```
string tempAddress = (await this.GetContract().GetFunction(
                    "ownerOf").CallAsync<string>(new object[] { index })).ToString();
```
I am still getting the same results:

ERROR - 11/27/2021 10:02:58 AM: Can not convert Object to String.
ERROR - 11/27/2021 10:02:58 AM:    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Nethereum.Contracts.ContractCall.CallAsync(CallInput callInput, BlockParameter block)
   at Nethereum.Contracts.FunctionBase.CallAsync[TReturn](CallInput callInput)
   at iNFT.src.Ethereum_Interact.TokenList() in
