### ISSUE TITLE
Missing support for the Polygon Mainnet (137 chain id

### ISSUE THREAD

**Issue by Rogaliusz** [Nethereum/Nethereum#750]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our gitter channel first. [Gitter](https://gitter.im/Nethereum/Nethereum)

Hey Guys!
I try to send some Matic by Nethereum API. In the js web3 solution, only need to change the network to 137 (here is a chainId). Calls work perfectly, I can fetch all information like balance, invoke smart contracts methods, and others.. 

Unfortunately, when I tried to send some Matic (function), it falls. 

## Expected Behavior
Working

## Current Behavior
```
Nethereum.JsonRpc.Client.RpcResponseException: invalid sender: eth_sendRawTransaction
   at Nethereum.JsonRpc.Client.ClientBase.HandleRpcError(RpcResponseMessage response, String reqMsg)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
   at Nethereum.Web3.Accounts.AccountSignerTransactionManager.SignAndSendTransactionAsync(TransactionInput transaction)
   at Nethereum.RPC.TransactionReceipts.TransactionReceiptPollingService.SendRequestAndWaitForReceiptAsync(Func`1 transactionFunction, CancellationTokenSource tokenSource)
   at Worker.Program.<Main>(String[] args)
```
## Possible Solution
I read something about the fact is Polygon is before BEP-1155. Here someone has a similar problem:
https://stackoverflow.com/questions/69384849/invalid-sender-on-signed-transaction-mumbai-polygon

## Steps to Reproduce
```C#
            var account = new Account(key, 137);
            var web3 = new Web3(account, polygonInfura);
            var balance = await web3.Eth.GetBalance.SendRequestAsync(someAddress);

            var networkId = await web3.Net.Version.SendRequestAsync(); // OK
            var transaction = await service
                .TransferEtherAndWaitForReceiptAsync(toAddress, 2, 50,
                    BigInteger.Parse("210000"));
```

**Comment by Rogaliusz** [comment]
Ok, got it. When is set to legacy mode & the gas fee is defined manually, the method returns always true. 

``` C#
        public bool IsTransactionToBeSendAsEIP1559(TransactionInput transaction)
        {
            return (!UseLegacyAsDefault && transaction.GasPrice == null) 
            || (transaction.MaxPriorityFeePerGas != null) 
            || (transaction.Type != null && transaction.Type.Value == TransactionType.EIP1559.AsByte());
        }
```

fixed by:
```C#
var account = new Account(key, 137);
var web3 = new Web3(account, polygonInfura);
var balance = await web3.Eth.GetBalance.SendRequestAsync(someAddress);
web3.TransactionManager.UseLegacyAsDefault = true;

var networkId = await web3.Net.Version.SendRequestAsync(); // OK
var transaction = await service.TransferEtherAndWaitForReceiptAsync(toAddress, 2);
```

**Comment by juanfranblanco** [comment]
@Rogaliusz Thanks for that, actually that check needs to change as a valid option is to have legacyMode and the gas price set. Normally for chains like this, the gasprice is automatically retrieved from the chain so just setting the legacyMode is ok.
