### ISSUE TITLE
大量请求EstimateGasAsync 出现超时

### ISSUE THREAD

**Issue by shunqiziran888** [Nethereum/Nethereum#790]
【测试】 EstimateGasAsync耗时:4/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:6/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
收到Ping
收到Ping
【127.0.0.1:6379/0】恢复检查时间：3/17/2022 6:25:24 PM
收到Ping
【异常说明】 Rpc timeout after 20000 milliseconds
【异常】    at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
   at Nethereum.Contracts.FunctionBase.EstimateGasFromEncAsync(CallInput callInput)
   at IMServerCore.SuperExtend.ETHCallContractFunWaitForTransactionHashAsync(Web3 web3, String contractAddress, String funName, Object[] extendedParameters)

**Comment by juanfranblanco** [comment]
EstimateGasAsync makes a connection via rpc, check that your url is correct 
EstimateGasAsync 通过 rpc 建立连接，检查您的 url 是否正确

**Comment by shunqiziran888** [comment]
win11 本地调试是正常的，linux下经常出现出现rpc time out  节点地址是正确的，因为刚开始的时候还是可以获取的，大量执行后就超时了！

**Comment by shunqiziran888** [comment]
Geth是不是有什么连接数的配置？ 我没找到，我在win上是可以正常使用的，linux下就rpc超时

**Comment by juanfranblanco** [comment]
Hmm maybe you are getting throttle, restricted on the number of connections, or the server cannot cope
嗯，也许您受到限制，连接数受到限制，或者服务器无法应对

**Comment by shunqiziran888** [comment]
额...Geth是我自己配置的， 需要设置什么参数么？ 处理一天了,实在搞不懂才来麻烦您！

**Comment by juanfranblanco** [comment]
不是，它可能不是操作系统的限制（在这种情况下是 linux，它的规格可能较低）
Not it doesnt it might the limitation of the OS (in this case linux, which may have a lower spec)

**Comment by juanfranblanco** [comment]
I am guessing now that you are running a local node
我现在猜你正在运行一个本地节点

**Comment by shunqiziran888** [comment]
是的 我是本地节点

**Comment by shunqiziran888** [comment]
获取Gas除了 EstimateGasAsync 还有其它方式么？

**Comment by juanfranblanco** [comment]
Then you might be hitting some hardware constraints, the timeout it is mainly showing that it cannot cope with more connections, originally thought that it was a public node, that it was stopping you.

那么你可能会遇到一些硬件限制，超时主要表明它无法处理更多的连接，最初认为它是一个公共节点，它正在阻止你。

**Comment by shunqiziran888** [comment]
好吧 谢谢，我在研究研究 .... 打扰了

**Comment by juanfranblanco** [comment]
并非如此，如果您知道要使用多少气体，您可以一直设置气体量，例如 Transfer.Gas = 100000。如果交易可能使用比预期更多的气体，由于逻辑等原因，您可以提供 更多的气体，它将被退还没有使用的东西。
Not really, if you know how much gas is going to be used you can set the amount of gas all the time for example Transfer.Gas = 100000. If the transaction may use more gas that expected, due to logic etc, you can provide a bigger amount of gas that it will be refunded what is not used.

**Comment by shunqiziran888** [comment]
这是我的LOG
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:9/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:53/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:4/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:9/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:4/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:9/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:3/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:16/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:4277/ms
【测试】 开始SendTransactionAsync
【测试】 SendTransactionAsync耗时:8/ms
【测试】 开始GetFunction
【测试】 GetFunction耗时:0/ms
【测试】 开始EstimateGasAsync
【测试】 EstimateGasAsync耗时:5486/ms

前面都很正常 最后两个EstimateGasAsync  耗时 4277/ms 和 5486/ms

**Comment by shunqiziran888** [comment]
目前来看不仅仅是 EstimateGasAsync ，现在所有的RPC请求都有此类问题，请求多了就time out！

**Comment by juanfranblanco** [comment]
有趣的是你知道调用的是什么函数吗？ 奇怪的是它需要很长时间。 智能合约调用有多复杂？

**Comment by shunqiziran888** [comment]
我在弄个window节点试试吧，不会是因为我服务器是机械硬盘的问题吧？

**Comment by juanfranblanco** [comment]
啊，是的，你同步时的性能会受到机械硬盘的影响，你需要一个 nvme

**Comment by shunqiziran888** [comment]
MaximumConnectionsPerServer 这里是20 是不是与这个有关？ 你的代码里
