### ISSUE TITLE
example code not working - https://docs.nethereum.com/en/latest/getting-started/

### ISSUE THREAD

**Issue by ronytesler** [Nethereum/Nethereum#798]
Exception is thrown when calling:`
            var balance = await web3.Eth.GetBalance.SendRequestAsync("0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae");`

Exception:
```
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s): eth_getBalance
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
   --- End of inner exception stack trace ---
   at Nethereum.JsonRpc.Client.RpcClient.SendAsync(RpcRequestMessage request, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendInnerRequestAsync[T](RpcRequestMessage reqMsg, String route)
   at Nethereum.JsonRpc.Client.ClientBase.SendRequestAsync[T](RpcRequest request, String route)
   at SafeHouseServer.Program.testAsync() in C:\Users\Rony\source\repos\SafeHouseServer\SafeHouseServer\Program.cs:line 13
   at SafeHouseServer.Program.Main(String[] args) in C:\Users\Rony\source\repos\SafeHouseServer\SafeHouseServer\Program.cs:line 23
```

**Comment by juanfranblanco** [comment]
You need to put your own infuraId https://infura.io/ sadly people have been abusing that id. Or just use the example directly from the playground http://playground.nethereum.com/

**Comment by ronytesler** [comment]
Thanks. Would be nice to add a comment to the docs.

**Comment by juanfranblanco** [comment]
@ronytesler yes the docs need a big re-visit. But first step the playground examples and then release the templates.
