### ISSUE TITLE
AggregateException -> RpcClientUnknownException -> System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by knocte** [Nethereum/Nethereum#94]
We're getting this exception sometimes (in Windows, using Microsoft's .NET framework):

```
System.AggregateException: One or more errors occurred. ---> EdjCase.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at EdjCase.JsonRpc.Client.RpcClient.d__23`2.MoveNext()
--- End of inner exception stack trace ---
at EdjCase.JsonRpc.Client.RpcClient.d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at EdjCase.JsonRpc.Client.RpcClient.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at Nethereum.Web3.FunctionBase.d__28`1.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
at BTCEX.Ethereum.Web3Client.GetContractBalance(Token token, String address) in C:\backend\BTCEX\BTCEX.Ethereum\Web3Client.cs:line 176
at BTCEX.Ethereum.TokenDepositClient.Run() in C:\backend\BTCEX\BTCEX.Ethereum\TokenDepositClient.cs:line 137
at BTCEX.Ethereum.TokenDepositClientRunner.timer_Elapsed(Object sender, ElapsedEventArgs e) in C:\backend\BTCEX\BTCEX.Ethereum\TokenDepositClient.cs:line 49
---> (Inner Exception #0) EdjCase.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at EdjCase.JsonRpc.Client.RpcClient.d__23`2.MoveNext()
--- End of inner exception stack trace ---
at EdjCase.JsonRpc.Client.RpcClient.d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at EdjCase.JsonRpc.Client.RpcClient.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at Nethereum.JsonRpc.Client.RpcRequestResponseHandler`1.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at Nethereum.Web3.FunctionBase.d__28`1.MoveNext()<---
```

At first I thought it was simply a timeout, but a timeout would just make Wait() return false, not throw TaskCanceledException.

Is NEthereum cancelling tasks in any place of the code? I don't find anything like this in the source so I'm confused.

**Comment by knocte** [comment]
Yikes, I think I've found that .NET throws this shitty chain of innerexceptions when there is a timeout:

http://stackoverflow.com/questions/12666922/distinguish-timeout-from-user-cancellation

**Comment by juanfranblanco** [comment]
Yes, I was looking into it and the http client seems to be the issue.
