### ISSUE TITLE
Swap two tokens on PancakeSwap

### ISSUE THREAD

**Issue by mahanamiri** [Nethereum/Nethereum#943]
Hello friends, I wanted to trade (swap) two tokens, for example, WBNB and Cake in Pancakeswap, and I typed the code sample below.
But unfortunately my code does not work.

```
var privateKey = "...";
        var account = new Account(privateKey);
        var web3 = new Web3(account, "https://bsc-dataseed1.binance.org:443");
        var routerAddress = "0x10ED43C718714eb63d5aA57B78B54704E256024E";
        var routerABI = @"[
            {
                ""inputs"": [
                    {
                        ""internalType"": ""address"",
                        ""name"": ""_factory"",
                        ""type"": ""address""
                    },
                    {
                        ""internalType"": ""address"",
                        ""name"": ""_WETH"",
                        ""type"": ""address""
                    }
                ],
                ""stateMutability"": ""nonpayable"",
                ""type"": ""constructor""
            },
            {
                ""inputs"": [],
                ""name"": ""WETH"",
                ""outputs"": [
                    {
                        ""internalType"": ""address"",
                        ""name"": """",
                        ""type"": ""address""
                    }
                ],
                ""stateMutability"": ""view"",
                ""type"": ""function""
            },
            {
                ""inputs"": [
                    {
                        ""internalType"": ""address"",
                        ""name"": ""sender"",
                        ""type"": ""address""
                    },
                    {
                        ""internalType"": ""address"",
                        ""name"": ""recipient"",
                        ""type"": ""address""
                    },
                    {
                        ""internalType"": ""uint256[]"",
                        ""name"": ""path"",
                        ""type"": ""uint256[]""
                    }
                ],
                ""name"": ""quote"",
                ""outputs"": [
                    {
                        ""internalType"": ""uint256"",
                        ""name"": """",
                        ""type"": ""uint256""
                    }
                ],
                ""stateMutability"": ""view"",
                ""type"": ""function""
            },
            {
                ""inputs"": [
                    {
                        ""internalType"": ""uint256"",
                        ""name"": ""amountIn"",
                        ""type"": ""uint256""
                    },
                    {
                        ""internalType"": ""uint256"",
                        ""name"": ""amountOutMin"",
                        ""type"": ""uint256""
                    },
                    {
                        ""internalType"": ""address[]"",
                        ""name"": ""path"",
                        ""type"": ""address[]""
                    },
                    {
                        ""internalType"": ""address"",
                        ""name"": ""to"",
                        ""type"": ""address""
                    },
                    {
                        ""internalType"": ""uint256"",
                        ""name"": ""deadline"",
                        ""type"": ""uint256""
                    }
                ],
                ""name"": ""swapExactTokensForTokens"",
                ""outputs"": [
                    {
                        ""internalType"": ""uint256[]"",
                        ""name"": """",
                        ""type"": ""uint256[]""
                    }
                ],
                ""stateMutability"": ""nonpayable"",
                ""type"": ""function""
            }
        ]";

        var router = web3.Eth.GetContract(routerABI,routerAddress);

        // Set up parameters for swapExactTokensForTokens function
        var wbnbAddress = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c";
        var cakeAddress = "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82";
        var amountIn = Web3.Convert.ToWei(1, UnitConversion.EthUnit.Ether);
        var amountOutMin = new BigInteger(0);
        var deadline = new BigInteger(DateTimeOffset.UtcNow.AddMinutes(10).ToUnixTimeSeconds());
        var path = new[] { wbnbAddress, cakeAddress };

        // Sign and send transaction to swap tokens
        var function = router.GetFunction("swapExactTokensForTokens");

        var gas = await function.EstimateGasAsync(web3, new CallInput()
        {
            From = account.Address,
            To = routerAddress,
            Data = function.CreateTransactionInput(routerAddress, amountIn, amountOutMin, path, account.Address, deadline).Data
        });

        var txInput = function.CreateTransactionInput(routerAddress, amountIn, amountOutMin, path, account.Address, deadline);
        txInput.Gas = new HexBigInteger(gas);
        var txHash = await web3.Eth.TransactionManager.SendTransactionAsync(txInput);

        Console.WriteLine($"Transaction sent: {txHash}");
```

**Comment by mahanamiri** [comment]
Error Result:

```
Nethereum.ABI.FunctionEncoding.AbiEncodingException
  HResult=0x80131500
  Message=An error occurred encoding abi value. Order: '1', Type: 'uint256', Value: 'Nethereum.Web3.Web3'.  Ensure the value is valid for the abi type.
  Source=Nethereum.ABI
  StackTrace:
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeAbiTypes(ABIType[] abiTypes, Object[] values)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeParameters(Parameter[] parameters, Object[] values)
   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest(String sha3Signature, Parameter[] parameters, Object[] values)
   at Nethereum.Contracts.FunctionBuilder.GetData(Object[] functionInput)
   at Nethereum.Contracts.Function.EstimateGasAsync(Object[] functionInput)
```

**Comment by mahanamiri** [comment]
I tried to use another sample code, unfortunately I got a new error, please guide me.

```
   var functionABI = @"[ { 'inputs': [ { 'internalType': 'address', 'name': '_factory', 'type': 'address' }, { 'internalType': 'address', 'name': '_WETH', 'type': 'address' } ], 'stateMutability': 'nonpayable', 'type': 'constructor' }, { 'inputs': [], 'name': 'WETH', 'outputs': [ { 'internalType': 'address', 'name': '', 'type': 'address' } ], 'stateMutability': 'view', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'tokenA', 'type': 'address' }, { 'internalType': 'address', 'name': 'tokenB', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'amountADesired', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountBDesired', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'addLiquidity', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'token', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'amountTokenDesired', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'addLiquidityETH', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' } ], 'stateMutability': 'payable', 'type': 'function' }, { 'inputs': [], 'name': 'factory', 'outputs': [ { 'internalType': 'address', 'name': '', 'type': 'address' } ], 'stateMutability': 'view', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveOut', 'type': 'uint256' } ], 'name': 'getAmountIn', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' } ], 'stateMutability': 'pure', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveOut', 'type': 'uint256' } ], 'name': 'getAmountOut', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' } ], 'stateMutability': 'pure', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' } ], 'name': 'getAmountsIn', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'view', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' } ], 'name': 'getAmountsOut', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'view', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveA', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'reserveB', 'type': 'uint256' } ], 'name': 'quote', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256' } ], 'stateMutability': 'pure', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'tokenA', 'type': 'address' }, { 'internalType': 'address', 'name': 'tokenB', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'removeLiquidity', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'token', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'removeLiquidityETH', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'token', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'removeLiquidityETHSupportingFeeOnTransferTokens', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'token', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' }, { 'internalType': 'bool', 'name': 'approveMax', 'type': 'bool' }, { 'internalType': 'uint8', 'name': 'v', 'type': 'uint8' }, { 'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32' }, { 'internalType': 'bytes32', 'name': 's', 'type': 'bytes32' } ], 'name': 'removeLiquidityETHWithPermit', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'token', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' }, { 'internalType': 'bool', 'name': 'approveMax', 'type': 'bool' }, { 'internalType': 'uint8', 'name': 'v', 'type': 'uint8' }, { 'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32' }, { 'internalType': 'bytes32', 'name': 's', 'type': 'bytes32' } ], 'name': 'removeLiquidityETHWithPermitSupportingFeeOnTransferTokens', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'address', 'name': 'tokenA', 'type': 'address' }, { 'internalType': 'address', 'name': 'tokenB', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' }, { 'internalType': 'bool', 'name': 'approveMax', 'type': 'bool' }, { 'internalType': 'uint8', 'name': 'v', 'type': 'uint8' }, { 'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32' }, { 'internalType': 'bytes32', 'name': 's', 'type': 'bytes32' } ], 'name': 'removeLiquidityWithPermit', 'outputs': [ { 'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapETHForExactTokens', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'payable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactETHForTokens', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'payable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactETHForTokensSupportingFeeOnTransferTokens', 'outputs': [], 'stateMutability': 'payable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactTokensForETH', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactTokensForETHSupportingFeeOnTransferTokens', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactTokensForTokens', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapExactTokensForTokensSupportingFeeOnTransferTokens', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountInMax', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapTokensForExactETH', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'inputs': [ { 'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256' }, { 'internalType': 'uint256', 'name': 'amountInMax', 'type': 'uint256' }, { 'internalType': 'address[]', 'name': 'path', 'type': 'address[]' }, { 'internalType': 'address', 'name': 'to', 'type': 'address' }, { 'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256' } ], 'name': 'swapTokensForExactTokens', 'outputs': [ { 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' } ], 'stateMutability': 'nonpayable', 'type': 'function' }, { 'stateMutability': 'payable', 'type': 'receive' } ]";

        var privatekey = "0...";

        Account account = new Account(privatekey);

        var web3 = new Web3(account, "https://bsc-dataseed1.binance.org:443");

        string contractaddress = "0x10ED43C718714eb63d5aA57B78B54704E256024E";
        var contract = web3.Eth.GetContract(functionABI, contractaddress);



     



        var function = contract.GetFunction("swapExactETHForTokens").CreateTransactionInput(account.Address, new object[] {
    new HexBigInteger(1000000000000000),
    new HexBigInteger(000000000),
    new [] { "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c", "Other Token Contract" },
    web3.TransactionManager.Account.Address,
     new HexBigInteger(DateTimeOffset.UtcNow.AddMinutes(50).ToUnixTimeSeconds())
});

        var gasPrice = await web3.Eth.GasPrice.SendRequestAsync();

        var nonce = await web3.Eth.Transactions.GetTransactionCount.SendRequestAsync(web3.TransactionManager.Account.Address);



        var transactionHash = await web3.TransactionManager.SendTransactionAsync(new TransactionInput
        {
            From = web3.TransactionManager.Account.Address,
            To = contractaddress,
            GasPrice = gasPrice,
            Gas = new HexBigInteger(100000),
            Value = new Nethereum.Hex.HexTypes.HexBigInteger(1000000000000000),
            Data = function.Data,
        });



        Console.WriteLine(transactionHash);
```

**Comment by mahanamiri** [comment]
Error Result:

```
System.Exception
  HResult=0x80131500
  Message=Too many arguments: 5 > 4
  Source=Nethereum.ABI
  StackTrace:
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeAbiTypes(ABIType[] abiTypes, Object[] values)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeParameters(Parameter[] parameters, Object[] values)
   at Nethereum.ABI.FunctionEncoding.FunctionCallEncoder.EncodeRequest(String sha3Signature, Parameter[] parameters, Object[] values)
   at Nethereum.Contracts.FunctionBuilder.GetData(Object[] functionInput)
   at Nethereum.Contracts.Function.CreateTransactionInput(String from, Object[] functionInput)
   at Program.<Main>d__1.MoveNext( 56

```

**Comment by juanfranblanco** [comment]
As per the comments in discord check https://github.com/Nethereum/Nethereum.Uniswap-V2-and-V3/blob/main/Nethereum.Uniswap.Testing/UniSwapV2PairTests.cs#L89

**Comment by mahanamiri** [comment]
Thank you for your reply, it was very helpful. I managed to send the BNB currency and receive the token, but another problem for me is that when I want to exchange the token, for example, cake to BNB, I have a problem. The problem is that to exchange the token to the currency of the network, PancakeSwap uses another contract and another FUNC.
Further information:
A contract that swaps COIN to tokens:
https://bscscan.com/address/0x10ed43c718714eb63d5aa57b78b54704e256024e
Method: Swap Exact ETH F...
This contract can't swap token to coin, there is a method for it, but it has a problem when it is called.
But the contract that swaps tokens to coins:
https://bscscan.com/address/0x13f4ea83d0bd40e75c8222255bc855a974568dd4#writeContract
Method: Multicall
