### ISSUE TITLE
SignTypedDataV4 fails if VerifyingContract is undefined

### ISSUE THREAD

**Issue by mrwillis** [Nethereum/Nethereum#944]
# SignTypedDataV4 fails if VerifyingContract is undefined

## Expected Behavior
It should skip absent optional fields

## Current Behavior
Error if verifyingContract is not supplied

## Steps to Reproduce

Something like this will fail with unhandled exception

```cs
   private static TypedData<Domain> GetTypedDefinition(BigInteger chainId)
        {
            return new TypedData<Domain>
            {
                Domain = new Domain
                {
                    Name = "Cancel",
                    Version = "1.0",
                    ChainId = chainId,
                },
                Types = new Dictionary<string, MemberDescription[]>
                {
                    ["EIP712Domain"] = new[]
                    {
                        new MemberDescription {Name = "name", Type = "string"},
                        new MemberDescription {Name = "version", Type = "string"},
                        new MemberDescription {Name = "chainId", Type = "uint256"},
                    },
                    ["Details"] = new[]
                    {
                        new MemberDescription {Name = "message", Type = "string"},
                        new MemberDescription {Name = "orders", Type = "string[]"},
                    },
                },
                PrimaryType = "Details",
            };
        }
```

later

```cs
 var mail = new Details
            {
                Message = PROMPT,
                Orders = orders
            };

            Console.WriteLine(mail.Orders.Count);
      
            var signature = _signer.SignTypedDataV4(mail, typedData, key); // fails
```

```
Unhandled exception. Nethereum.ABI.FunctionEncoding.AbiEncodingException: An error occurred encoding abi value. Order: '1', Type: 'address', Value: 'null'.  Ensure the value is valid for the abi type.
 ---> System.Exception: Invalid value for type 'Nethereum.ABI.Encoders.IntTypeEncoder'. Value: null, ValueType: ()
   at Nethereum.ABI.Encoders.IntTypeEncoder.Encode(Object value, UInt32 numberOfBytesArray)
   at Nethereum.ABI.Encoders.AddressTypeEncoder.Encode(Object value)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeAbiTypes(ABIType[] abiTypes, Object[] values)
   --- End of inner exception stack trace ---
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeAbiTypes(ABIType[] abiTypes, Object[] values)
   at Nethereum.ABI.FunctionEncoding.ParametersEncoder.EncodeParameters(Parameter[] parameters, Object[] values)
   at Nethereum.ABI.EIP712.Eip712TypedDataEncoder.EncodeData(BinaryWriter writer, IDictionary`2 types, IEnumerable`1 memberValues)
   at Nethereum.ABI.EIP712.Eip712TypedDataEncoder.HashStruct(IDictionary`2 types, String primaryType, IEnumerable`1 message)
   at Nethereum.ABI.EIP712.Eip712TypedDataEncoder.EncodeTypedDataRaw(TypedDataRaw typedData)
   at Nethereum.ABI.EIP712.Eip712TypedDataEncoder.EncodeTypedData[T,TDomain](T message, TypedData`1 typedData)
   at Nethereum.Signer.EIP712.Eip712TypedDataSigner.EncodeTypedData[T,TDomain](T message, TypedData`1 typedData)
   at Nethereum.Signer.EIP712.Eip712TypedDataSigner.SignTypedDataV4[T,TDomain](T message, TypedData`1 typedData, EthECKey key)
```

## Context (Environment)

Trying to sign EIP712 Payloads excluding verifyContrac

## Detailed Description
If you see here

https://eips.ethereum.org/EIPS/eip-712

In `Definition of domainSeparator` `verifyingContract` is technically optional. Actually all of these fields are optional. Currently the implementation forces `verifyingContract` to be supplied, also `salt` is not supported.

**Comment by mrwillis** [comment]
My mistake. There are other subclasses
