### ISSUE TITLE
PancakeSwap websocket drops connection using the SubscribeAndRunAsync example 

### ISSUE THREAD

**Issue by sadhippo** [Nethereum/Nethereum#949]
Issue tracker is **ONLY** used for reporting bugs. New features, questions and support should be discussed on our discord channel first. [Discord](https://discord.gg/u3Ej2BReNn )

## Expected Behavior

The Pancake Swap websocket maintains connections

## Current Behavior
PancakeSwap aborts connection and cannot reconnect after a varying amount of time. 
UniSwap websocket maintains connection using same function.

## Steps to Reproduce

1. Using the provided code below, while statement to ping server seems to throw error, same as example code
1. Drops connection after a successful 5 or so minutes(varies) of being connected
1.
1.

## Context (Environment)

PancakeSwap aborts connection and cannot reconnect after a varying amount of time. 
Uniswap maintains connection using same function.

## Detailed Description

Using this example for PancakeSwap: https://github.com/Nethereum/Nethereum.Templates.WebSocketStreaming/blob/master/ExampleLogsUniswapSyncSubscription.cs#L70

After 5-10 minutes, the connection aborts and cannot be reconnected to after 4 attempts.

Error message:
```
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred trying to send web socket requests(s)
---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequestMessage request, IRpcStreamingResponseHandler requestResponseHandler, String route)
--- End of inner exception stack trace ---
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequestMessage request, IRpcStreamingResponseHandler requestResponseHandler, String route)
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequest request, IRpcStreamingResponseHandler requestResponseHandler, String route)
```

It seems like it is happening in the while statement at the bottom 

```
"public async void SubscribeSwapEvent()
        {
            var swapEvent = _web3.Eth.GetEvent<SwapEventDTO>(_pairAddress);
            var swapEventFilter = swapEvent.CreateFilterInput();
            unsubFlag = false;

            using (var client = new StreamingWebSocketClient(_web3SocketAddress))
            {
                var subscription = new EthLogsObservableSubscription(client);
                subscription.GetSubscriptionDataResponsesAsObservable().
                             Subscribe(log =>
                             {
                                 try
                                 {
                                     EventLog<SwapEventDTO> decoded = Event<SwapEventDTO>.DecodeEvent(log);
                                     if (decoded != null && swapEvent != null)
                                         pairSwapEvent.Invoke(decoded.Event);
                                     else
                                     {
                                         this.Debug("Found no standard transfer log");
                                     }
                                 }
                                 catch (Exception ex)
                                 {
                                     ex.CatchException("Log Address: " + log.Address + " is not a standard transfer log.");
                                 }
                             });

                await client.StartAsync();
                subscription.GetSubscribeResponseAsObservable().Subscribe(id => {
                    this.Debug($"Subscribed with id: {id}");
                    });
                await subscription.SubscribeAsync(swapEventFilter);

                //Keep connection alive with RPC and check for unsub flag if user decided to unsubscribe
                while (!unsubFlag)
                {
                    var handler = new EthBlockNumberObservableHandler(client);
                    handler.GetResponseAsObservable().Subscribe(x => this.Debug("Block observer value: " + x.Value));
                    await handler.SendRequestAsync();
                    Thread.Sleep(15000);
                }

                await subscription.UnsubscribeAsync();
            }
        }"
```

**Comment by juanfranblanco** [comment]
@sadhippo is uniswap using ethereum mainnet and pancake binance ? If keeping the connection alive does not work with this, I would suggest to contact the binance chain guys and see what change have they made to geth that does not allow to keep the connections alive even with 15 seconds intervals.

**Comment by sadhippo** [comment]
Thanks for the reply @juanfranblanco , I appreciate, will report back if I learn anything

**Comment by juanfranblanco** [comment]
@sadhippo Thanks, Let me know if I need to do something on my end.
